### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by z3214965** [fanvanzh/3dtiles#1]
你好：
我想做个osgbTo3DTiles工具，对你的这个项目非常感兴趣，但我不知道如何编译成3dtile.exe，希望你能告知，谢谢！

**Comment by fanvanzh** [comment]
# 编译说明：
1、安装 vs 2015 或 vc 2015 c++ build tools。
2、设置 rustup 的代理： 
RUSTUP_DIST_SERVER=http://mirrors.ustc.edu.cn/rust-static
RUSTUP_UPDATE_ROOT=http://mirrors.ustc.edu.cn/rust-static/rustup
3、下载 rustup-init.exe 自动安装工具并按默认执行， 链接： [rustup_init.exe](https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe)
4、配置依赖源的代理：创建文件 C:/Users/<用户名>/.cargo/config (没有后缀）, 内容如下。
```
[registry]
index = "https://mirrors.ustc.edu.cn/crates.io-index/"
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'ustc'
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index/"
```
5、命令行进入 3dtile 目录，执行命令：
`cargo build --release`
6、编译好的结果在 3dtile/target/release 目录

**Comment by z3214965** [comment]
谢谢！
