### ISSUE TITLE
build时引用的源update 失败了，请问如何解决？

### ISSUE THREAD

**Issue by lorilee** [fanvanzh/3dtiles#10]
![tim 20180403134155](https://user-images.githubusercontent.com/11283143/38231407-0afd7f30-3745-11e8-8865-72b59b1a312d.jpg)

**Comment by lorilee** [comment]
![image](https://user-images.githubusercontent.com/11283143/38233928-d46a8e4a-374e-11e8-99f2-3b0059199ffd.png)
这里用编译好的程序转换osgb 数据虽然显示完成了，但是看不到转换后的数据，另外就是有时候会保持显示的 os error？请问这要怎样解决？

**Comment by fanvanzh** [comment]
1. 你应该没有按照安装指导上配置好 config 文件。
2. 你数据的 metadata 坐标不是经纬度的，你可以在程序里指定 xy 的坐标。
3. 可以发一下 metadata. xml 的内容，方便作者扩展多坐标系支持。

**Comment by fanvanzh** [comment]
另外 os error 的详细信息能发下不？

**Comment by lorilee** [comment]
![image](https://user-images.githubusercontent.com/11283143/38283475-c63160f2-37e8-11e8-951f-3d1dd130d0b9.png)

![image](https://user-images.githubusercontent.com/11283143/38283455-b1512618-37e8-11e8-8ae4-7fb1371f76f4.png)
config 是安装readme中说明的配置了的，放在.cargo的目录下的，看错误应该是依赖的chrono不能加载到

**Comment by lorilee** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	
	<SRS>EPSG:32650</SRS>
	
	<SRSOrigin>400821,3324152,0</SRSOrigin>
	<Texture>
		<ColorSource>Visible</ColorSource>
	</Texture>
</ModelMetadata>

meta文件是这个样子的

**Comment by lorilee** [comment]
os error 的那个错误好像触发不了了

**Comment by lorilee** [comment]
找到原因了，原来是被comodo的沙盒给干掉了
