### ISSUE TITLE
倾斜摄影转为3d-tiles，在cesium加载是悬空的？怎么处理，变换？

### ISSUE THREAD

**Issue by limzgiser** [fanvanzh/3dtiles#103]
请问一下，我转出的3d切片，在cesium加载是悬空的，没有贴合地面。转换前offset参数设置的是0，为什么是悬空的，请问一下，怎么变换处理一下？

**Comment by fanvanzh** [comment]
offset 写成负数试试 ， 可能你的模型底部有碎小的面片。

**Comment by limzgiser** [comment]
谢谢你的回答，确实有碎面片，这样做，整个模型会在拖动场景的时候移动，回头处理一下数据。顺便再请问一个问题，如何把手工大场景的模型做成3D切片(LOD)？谢谢。
