### ISSUE TITLE
vs2015编译错误

### ISSUE THREAD

**Issue by yzthr** [fanvanzh/3dtiles#105]
vs2015编译工程出现与[Build Error #5](https://github.com/fanvanzh/3dtiles/issues/5)类似的错误，代码是直接clone的，系统信息:win10专业版，vs2015u3。
错误信息如下：
![pic](https://github.com/yzthr/pic/blob/master/screenshot.png)

**Comment by fanvanzh** [comment]
请确认环境是 vs2015 update 3 x64， 代码是 git clone 下来的吗？

**Comment by yzthr** [comment]
> 请确认环境是 vs2015 update 3 x64， 代码是 git clone 下来的吗？

您好，这个可以确认

**Comment by fanvanzh** [comment]
你可以用 vs2015 的命令提示符：
`cl -I 头文件目录 osgb23dtile.cpp`
编译下试试。
