### ISSUE TITLE
层级跳转误差bug

### ISSUE THREAD

**Issue by simonasdmd** [fanvanzh/3dtiles#107]
元数据osgb有16到22级七个级别。转换出来对应文件数量和tileset.json索引没有问题。但是视距最远时为16级（正确），逐步拉近层级没有变换，拉到最近时直接显示为22级。中间的层级没有显示。
这么远时为16级正常。
![image](https://user-images.githubusercontent.com/42527845/65757234-4e0f5280-e149-11e9-9c58-2bc86f9a3de7.png)
然后拉至极近，仍然是16级 不正常，数据没有层级跳转
![image](https://user-images.githubusercontent.com/42527845/65757310-78f9a680-e149-11e9-892c-bf751bdaaf7a.png)
最终再次拉近直接跳转到22级，中间的 17 18 19 20 21没有显示过
![image](https://user-images.githubusercontent.com/42527845/65757349-89118600-e149-11e9-8f8c-9cc242272915.png)

想问下这个是不是由geometricError的算法误差引起的
原osgb数据
[test_osgb.zip](https://github.com/fanvanzh/3dtiles/files/3661923/test_osgb.zip)
生成的3dtiles数据
[test_osgb_3dtiles.zip](https://github.com/fanvanzh/3dtiles/files/3661925/test_osgb_3dtiles.zip)

**Comment by fanvanzh** [comment]
有可能，你看下 17 -> 21 级的 GeometricError 是不是都一样。

**Comment by simonasdmd** [comment]
double get_geometric_error(int lvl ){
    const double pi = std::acos(-1);
    double round = 2 * pi * 6378137.0 / 128.0;
    return round / std::pow(2.0, lvl );
}

我看到这个是计算GeometricError 的。问下这个为什么要除128而不是180呢？

**Comment by simonasdmd** [comment]
@fanvanzh 
double get_geometric_error(int lvl ){
const double pi = std::acos(-1);
double round = 2 * pi * 6378137.0 / 128.0;
return round / std::pow(2.0, lvl );
}

我看到这个是计算GeometricError 的。问下这个为什么要除128而不是180呢？

**Comment by fanvanzh** [comment]
哦，那应该是 180.
可能写错了

**Comment by fanvanzh** [comment]
你用的是 vs 分支的代码吗？
试试 master 命令行的，或者下载预编译结果。
