### ISSUE TITLE
转换后的数据加载到cesium时错误，RuntimeError: Unsupported glTF Extension: KHR_technique_webgl

### ISSUE THREAD

**Issue by CHENJIAMIAN** [fanvanzh/3dtiles#111]

**Comment by CHENJIAMIAN** [comment]
[https://zhuanlan.zhihu.com/p/46189487](url)
需要用此文章来这个文件来

修复才行

**Comment by fanvanzh** [comment]
是最新版本吗？
1.50 格式支持已更新，请在项目首页下载 prebuild

**Comment by CHENJIAMIAN** [comment]
直接下的master分支[https://github.com/fanvanzh/3dtiles/archive/master.zip](url)

**Comment by fanvanzh** [comment]
使用 rust 编译的命令行工具吗？
别用 C# 那个，那个好久没更新了。

**Comment by yankai12** [comment]
https://blog.csdn.net/yk583443123/article/details/103403238
