### ISSUE TITLE
数据量如果上几十G,加载特别慢

### ISSUE THREAD

**Issue by yankai12** [fanvanzh/3dtiles#112]
这个问题有啥好的方案？

**Comment by fanvanzh** [comment]
投资提高带宽

**Comment by yankai12** [comment]
我试了一下，请求几乎已经到了峰值，或许，未来5G或者6G可以解决这个问题
我觉得可能优化的方面
从数据层面，合并顶层的数据，减少请求次数这样是否也是可以的？

**Comment by fanvanzh** [comment]
顶层用个 俯视Image 不也一样吗？
Google Earth 也是 Image 切换 倾斜摄影， 倾斜摄影 切换 街景。

**Comment by yankai12** [comment]
你的意思是Cesium同时加载图片和3dtiles?

**Comment by yankai12** [comment]
等模型OK 了把图片去掉

**Comment by yankai12** [comment]
今天我试着去节点，效果有不太明显，
不知道这样可行不，第一层的b3dm合成一个文件或者将OSGB的第一层数据合并成一个，加载的时候直接加载这一个合成的b3dm，后面基层还是按照之前的策略

**Comment by fanvanzh** [comment]
可以啊，碎片合并成整体、应该会快很多。

**Comment by yankai12** [comment]
可以加您微信么？ yankai2017------------------ 原始邮件 ------------------
发件人: "fanvanzh"<notifications@github.com>
发送时间: 2019年12月12日(星期四) 上午9:44
收件人: "fanvanzh/3dtiles"<3dtiles@noreply.github.com>;
抄送: "yankai12"<614018819@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fanvanzh/3dtiles] 数据量如果上几十G,加载特别慢 (#112)



可以啊，碎片合并成整体、应该会快很多。
 
&mdash;
