### ISSUE TITLE
是否支持mac下编译

### ISSUE THREAD

**Issue by ali322** [fanvanzh/3dtiles#117]
手上没win机器,很头疼

**Comment by fanvanzh** [comment]
应该可以。
rust 是跨平台的， 你找个 mac 的 gdal、osg库，就可以了

**Comment by ali322** [comment]
麻烦提供下对应的版本号

**Comment by ali322** [comment]
![图片](https://user-images.githubusercontent.com/780693/70985156-a45fb200-20f6-11ea-9435-1cbe7d74a53c.png)

mac 编译报错

**Comment by fanvanzh** [comment]
gdal、osg 的版本， 可以查看项目里对应头文件的 version.h 等信息。

另外你还要修改下：
3dtiles/build.rs
增加下 Mac 环境下的编译指令。

**Comment by ali322** [comment]
```rust
match env::var("TARGET") {
        Ok(val) => {
            match val.as_str() {
                "x86_64-pc-windows-gnu" => build_win_gun(),
                "x86_64-unknown-linux-gnu" => build_linux_unkonw(),
                "x86_64-pc-windows-msvc" => build_win_msvc(),
                &_ => {}
            }
        }
        _ => {}
    }
```

这里怎么添加? `target`是啥,我直接这样`"x86_64-unknown-darwin-gnu" => build_linux_unkonw(),` 可以吗
