### ISSUE TITLE
如何转一个threejs支持的gltf格式

### ISSUE THREAD

**Issue by longwind91** [fanvanzh/3dtiles#119]
您好，使用您提供的方法，转出gltf2.0的extensions为KHR_techniques_webgl，只能供cesium使用，请问能否支持three.js的gltfloader，比如下列之一：
KHR_draco_mesh_compression
KHR_materials_pbrSpecularGlossiness
KHR_materials_unlit
KHR_mesh_quantization
KHR_lights_punctual
KHR_texture_transform
MSFT_texture_dds。

**Comment by fanvanzh** [comment]
对不起，不支持。
这些都是 KHR 高级扩展。

**Comment by bim2box** [comment]
> 您好，使用您提供的方法，转出gltf2.0的extensions为KHR_techniques_webgl，只能供cesium使用，请问能否支持three.js的gltfloader，比如下列之一：
> KHR_draco_mesh_compression
> KHR_materials_pbrSpecularGlossiness
> KHR_materials_unlit
> KHR_mesh_quantization
> KHR_lights_punctual
> KHR_texture_transform
> MSFT_texture_dds。

@longwind91 Please give https://bim2box.com a try, which supports KHR_draco_mesh_compression

**Comment by xiemeilong** [comment]
能不能加一个不使用KHR_techniques_webgl扩展的选项，deck.gl支持3dtile，但是不支持KHR_techniques_webgl扩展。

**Comment by fanvanzh** [comment]
> @fanvanzh fanvanzh 能不能加一个不使用KHR_techniques_webgl扩展的选项，deck.gl支持3dtile，但是不支持KHR_techniques_webgl扩展。

你可以删除代码中 KHR_techniques_webgl 相关的部分。

**Comment by xiemeilong** [comment]
@fanvanzh 没有KHR_techniques_webgl扩展支持的时候贴图会加载不出来，我直接把KHR_techniques_webgl 相关的部分删掉的话，会不会依然无法加载贴图？

**Comment by fanvanzh** [comment]
本项目中 KHR_techniques_webgl 只是引用了着色器相关部分， 删掉后材质可以用 gltf 2.0 的标准，贴图应该是有的。

**Comment by fanvanzh** [comment]
> @fanvanzh 没有KHR_techniques_webgl扩展支持的时候贴图会加载不出来，我直接把KHR_techniques_webgl 相关的部分删掉的话，会不会依然无法加载贴图？

搜索下这个关键字，打开 if 开关走上面的流程就可以了。
```
// use shader material
```

**Comment by xiemeilong** [comment]
@fanvanzh  非常感谢，但是我编译总过不去。报错中还出现了我电脑上没有的路径 `f:\dd\vctools\compiler\cxxfe\sl\p1\c\main.c`

```
  Compiling num-integer v0.1.44
   Compiling termcolor v1.1.2
   Compiling regex v1.4.2
   Compiling clap v2.33.3
error: failed to run custom build command for `_3dtile v0.1.0 (D:\root\source\3dtiles)`

Caused by:
  process didn't exit successfully: `D:\root\source\3dtiles\target\release\build\_3dtile-c195c9fbc960f24d\build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-pc-windows-msvc")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("false")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoD:\\root\\source\\3dtiles\\target\\release\\build\\_3dtile-9d85aef444ae72f9\\out\\./src/tileset.o" "-c" "./src/tileset.cpp"
tileset.cpp
./src/tileset.cpp: fatal error C1073: Internal error involving incremental compilation(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\main.c', line 882)
exit code: 2

--- stderr


error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoD:\\root\\source\\3dtiles\\target\\release\\build\\_3dtile-9d85aef444ae72f9\\out\\./src/tileset.o" "-c" "./src/tileset.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).



warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by fanvanzh** [comment]
config 中新增了pbr开关配置:
3dtile.exe -f osgb -i xx -o xx -c "{\"pbr\": true}"

**Comment by fanvanzh** [comment]
使用 KHR_materials_unlit 代替 KHR_technique_webgl。
fe04fb5ac99ceb4b76f732cceb3c9df434827cdf
