### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by helen00** [fanvanzh/3dtiles#12]
您好，vs2015运行报错，请问您是什么环境，能否出个工程

![image](https://user-images.githubusercontent.com/28391325/38619258-5ad8e820-3dce-11e8-8bf9-1e57b1eb8e09.png)

**Comment by fanvanzh** [comment]
这个看上去不是我的工程，是你自己拉的 tinygltf 编译的。
请仔细排查下，你的工程配置，代码逻辑。
