### ISSUE TITLE
编译错误_ undefined reference

### ISSUE THREAD

**Issue by yu969890202** [fanvanzh/3dtiles#122]
你好，按照你的编译步骤，执行cargo build --release 命令的时候出现错误， undefined reference to `osgb23dtile_path'，其它类似的语法也出现该错误！

**Comment by Hisos** [comment]
我的也有同样的问题
undefined reference to `osgb23dtile_path'
undefined reference to `degree2rad'
undefined reference to `transform_c'
undefined reference to `shp23dtile'
undefined reference to `make_gltf'
undefined reference to `epsg_convert'

**Comment by Hisos** [comment]
找到原因了，需要把编译链接工具设置为msvc，之前是gnu的。
方法为：在命令行终端输入"rustup default stable-x86_64-pc-windows-msvc"。
我怎么知道最后输入这个命令？一开始输入rustup命令，会显示帮助文档，根据帮助文档不难解决这个问题。

**Comment by yu969890202** [comment]
@Hisos 大神厉害，帮我解决了一个头疼的问题，多谢！
