### ISSUE TITLE
请求rust代码中增加读取metadata.xml 中的wkt 投影坐标功能

### ISSUE THREAD

**Issue by zhoulihe1981** [fanvanzh/3dtiles#123]
有一批osgb 数据， 坐标是beijing54 投影， 在epsg 中没有对应。 是wkt标准的投影定义， 现在需要在
error!("SRS content error"); 位置添加解析metadata的数据，调用osgb.rs中添加的定义
pub fn wkt_convert(gdal:*const u8, val: *mut f64, gdal:*const i8) -> bool;

然后调用
tileset.cpp , 我在其中添加了一个函数

extern "C" bool wkt_convert(char* wkt, double* val, char* path) {
    CPLSetConfigOption("GDAL_DATA", path);
    OGRSpatialReference inRs,outRs;
    inRs.importFromWkt(&wkt);
    outRs.importFromEPSG(4326);
    OGRCoordinateTransformation *poCT = OGRCreateCoordinateTransformation( &inRs, &outRs );
    if (poCT) {
        if (poCT->Transform( 1, val, val + 1)) {
            delete poCT;
            return true;
        }
        delete poCT;
    }
    return false;
} 

metadata.xml 内容：
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	
	<SRS>PROJCS[&quot;Beijing 1954 / 3-degree Gauss-Kruger CM 121E&quot;,    GEOGCS[&quot;Beijing 1954&quot;,        DATUM[&quot;Beijing_1954&quot;,            SPHEROID[&quot;Krassowsky 1940&quot;,6378245,298.3,                AUTHORITY[&quot;EPSG&quot;,&quot;7024&quot;]],            TOWGS84[15.8,-154.4,-82.3,0,0,0,0],            AUTHORITY[&quot;EPSG&quot;,&quot;6214&quot;]],        PRIMEM[&quot;Greenwich&quot;,0,            AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],        UNIT[&quot;degree&quot;,0.0174532925199433,            AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],        AUTHORITY[&quot;EPSG&quot;,&quot;4214&quot;]],    PROJECTION[&quot;Transverse_Mercator&quot;],    PARAMETER[&quot;latitude_of_origin&quot;,0],    PARAMETER[&quot;central_meridian&quot;,121],    PARAMETER[&quot;scale_factor&quot;,1],    PARAMETER[&quot;false_easting&quot;,100000],    PARAMETER[&quot;false_northing&quot;,-3500000],    UNIT[&quot;metre&quot;,1,        AUTHORITY[&quot;EPSG&quot;,&quot;9001&quot;]],    AUTHORITY[&quot;EPSG&quot;,&quot;2437&quot;]]</SRS>
	
	<SRSOrigin>90943,35568,0</SRSOrigin>
	<Texture>
		<ColorSource>Visible</ColorSource>
	</Texture>
</ModelMetadata>

**Comment by zhoulihe1981** [comment]
增加能够解析proj4 以及wkt投影功能其实不难, 关键时不懂rust, 实在不行就要只能用qt重新main了

**Comment by zhoulihe1981** [comment]
main.rs
在error!("SRS content error"); 位置添加
let mut pt: Vec<f64> = metadata.SRSOrigin
                            .split(",")
                            .map(|v| v.parse().unwrap())
                            .collect();
                        if pt.len() >= 2 {
                                let gdal_data: String =  {
                                    use std::path::Path;
                                    let exe_dir = ::std::env::current_exe().unwrap();
                                    Path::new(&exe_dir).parent().unwrap()
                                    .join("gdal_data").to_str().unwrap().into()
                                };
                            unsafe {
                                use std::ffi::CString;
                                let wkt : String = metadata.SRS;
                                println!("{:?}", wkt);
                                let c_str = CString::new(gdal_data).unwrap();
                                let ptr = c_str.as_ptr();
                                let wktPtr = wkt.as_ptr();
                                if osgb::wkt_convert(wktPtr, pt.as_mut_ptr(),ptr) {
                                    center_x = pt[0];
                                    center_y = pt[1];
                                    info!("epsg: x->{}, y->{}", pt[0], pt[1]);
                                } else {
                                    error!("epsg convert failed!");
                                }
                            }    
                        }

osgb.rs
添加
pub fn wkt_convert(gdal:*const u8, val: *mut f64, gdal:*const i8) -> bool;

tileset.cpp
添加
extern "C" bool wkt_convert(char* wkt, double* val, char* path) {
    CPLSetConfigOption("GDAL_DATA", path);
    OGRSpatialReference inRs,outRs;
    inRs.importFromWkt(&wkt);
    outRs.importFromEPSG(4326);
    OGRCoordinateTransformation *poCT = OGRCreateCoordinateTransformation( &inRs, &outRs );
    if (poCT) {
        if (poCT->Transform( 1, val, val + 1)) {
            delete poCT;
            return true;
        }
        delete poCT;
    }
    return false;
} 

编译通过, 加载位置也对, 高度好像高了50米, 在软件里面调整了一下海拔高度, 不懂rust, 也不敢提交. 哪位高手懂rust的测试一下, 提交进去

**Comment by fanvanzh** [comment]
Meger the PR.
Please follow the prebuild link, and have a try。
