### ISSUE TITLE
您好，这个工具只是做了osgb2b3dm的切片，没有进行LOD处理吧

### ISSUE THREAD

**Issue by yankai12** [fanvanzh/3dtiles#124]
我用这个工具加载一块区域的倾斜摄影，浏览器的内存高达1300MB

**Comment by zhoulihe1981** [comment]
分块和lod是osgb本身做的吧? 这个工具只是根据osgb的分块和lod做转换

**Comment by fanvanzh** [comment]
是的，没做lod，lod是 osgb 文件本身做的。
浏览器内存 1.3G 应该正常状态。

**Comment by yankai12** [comment]
smart3D 做的，加载下来只有200M，这是因为LOD的问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fanvanzh"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 中午12:01
收件人: "fanvanzh/3dtiles"<3dtiles@noreply.github.com&gt;; 
抄送: "上善若水"<614018819@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fanvanzh/3dtiles] 您好，这个工具只是做了osgb2b3dm的切片，没有进行LOD处理吧 (#124)




是的，没做lod，lod是 osgb 文件本身做的。
 浏览器内存 1.3G 应该正常状态。
