### ISSUE TITLE
Unsupported glTF Extension: KHR_technique_webgl

### ISSUE THREAD

**Issue by myhnuhai** [fanvanzh/3dtiles#128]
用最新版本转换OSGB数据之后用Cesium加的时候报Unsupported glTF Extension: KHR_technique_webgl这个错误。

**Comment by fanvanzh** [comment]
下载项目 ReadMe 里的 prebuild 链接。
不要下载 Release 的。

**Comment by njchenyi** [comment]
> 下载项目 ReadMe 里的 prebuild 链接。
> 不要下载 Release 的。

我下载了ReadMe里面的prebuild链接，解压后运行，转换出来的数据也是报Unsupported glTF Extension: KHR_technique_webgl

**Comment by fanvanzh** [comment]
按理说不会啊，代码里都搜不到 KHR_technique_webgl 关键字。
是不是数据有缓存？

**Comment by fanvanzh** [comment]
# use pbr-texture
3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{\"pbr\": true}"
