### ISSUE TITLE
编译不通，谁知道这是什么问题呢？

### ISSUE THREAD

**Issue by hqr1688** [fanvanzh/3dtiles#130]
= note: E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.15.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x111e): undefined reference to `osgb23dtile_path'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.15.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x3845): undefined reference to `degree2rad'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.15.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x3861): undefined reference to `degree2rad'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.15.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x3db2): undefined reference to `transform_c'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.5.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x2e95): undefined reference to `make_gltf'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.5.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x3b93): undefined reference to `wkt_convert'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.5.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x42ba): undefined reference to `epsg_convert'
          E:\3dtiles\target\release\deps\3dtile-83544ef4f1ad93f6.3dtile.ekzj3nbz-cgu.6.rcgu.o:3dtile.ekzj3nbz-cg:(.text+0x3971): undefined reference to `shp23dtile'

error: aborting due to previous error
error: could not compile `3dtile`.

**Comment by hqr1688** [comment]
用下面这个命令切换toolchain为msvc后，也还是编译不通。
rustup default stable-x86_64-pc-windows-msvc


error: failed to run custom build command for `3dtile v0.1.0 (E:\3dtiles)`

Caused by:
  process didn't exit successfully: `E:\3dtiles\target\release\build\3dtile-3752960a757c44a3\build-script-build` (exit code: 1)
--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoE:\\3dtiles\\target\\release\\build\\3dtile-c23e456580c561b9\\out\\./src/osgb23dtile.o" "-c" "./src/osgb23dtile.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by hqr1688** [comment]
有人编译过吗？到底要怎么编译呢？

**Comment by hqr1688** [comment]
已经解决，竟然是代码中几行中文注释引起的，改了一下注释就好了。

**Comment by ZhangJiankang2008** [comment]
目测我的和你的一样的问题， 具体哪几行代码啊？

**Comment by ZhangJiankang2008** [comment]
错误信息里有， 涉及两个文件 src/osgb23dtile.cpp和 src/make_gltf.cpp

**Comment by weiyu666** [comment]
编译不通过，删除中文注释也没有用！src/osgb23dtile.cpp和 src/make_gltf.cpp

**Comment by weiyu666** [comment]
E:\3dtiles>cargo build
   Compiling 3dtile v0.1.0 (E:\3dtiles)
error: failed to run custom build command for `3dtile v0.1.0 (E:\3dtiles)`

Caused by:
  process didn't exit successfully: `E:\3dtiles\target\debug\build\3dtile-768e4c95be29643c\build-script-build` (exit code: 1)
--- stderr


error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" 
"-nologo" "-MD" "-Z7" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoE:\\3dtiles\\target\\debug\\build\\3dtile-182798b46784c6c1\\out\\./src/tileset.o" "-c" "./src/tileset.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

**Comment by weiyu666** [comment]
怎么回事有没有人知道？

**Comment by fanvanzh** [comment]
请参考：
https://github.com/fanvanzh/3dtiles/wiki/How-to-build

**Comment by ydyvip** [comment]
src/earcut.hpp 头部加上 #include <limits>
