### ISSUE TITLE
没有办法转换Z值

### ISSUE THREAD

**Issue by RS-Hong** [fanvanzh/3dtiles#133]
我在osgb的metadata.xml中设置了
![image](https://user-images.githubusercontent.com/58028722/77378873-393b1100-6db2-11ea-8b85-1d7346b79ce8.png)
我将其加载cesium中发现高程的值与Z值设置为0时一样，是正常的吗

**Comment by fanvanzh** [comment]
代码里没读取 xml 里的z值。
可以通过命令行参数设置Z值，见 Readme 中  -c "offset":  的部分。
