### ISSUE TITLE
VS调试编译不过有人知道怎么回事吗？

### ISSUE THREAD

**Issue by weiyu666** [fanvanzh/3dtiles#136]
E:\3dtiles>cargo build
   Compiling 3dtile v0.1.0 (E:\3dtiles)
error: failed to run custom build command for `3dtile v0.1.0 (E:\3dtiles)`

Caused by:
  process didn't exit successfully: `E:\3dtiles\target\debug\build\3dtile-768e4c95be29643c\build-script-build` (exit code: 1)
--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" 
"-nologo" "-MD" "-Z7" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoE:\\3dtiles\\target\\debug\\build\\3dtile-182798b46784c6c1\\out\\./src/tileset.o" "-c" "./src/tileset.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

**Comment by theonewang** [comment]
@weiyu666 wish to know how to solve this problem?thank you
