### ISSUE TITLE
大疆无人机扫的倾斜摄影osgb转b3dm，有json文件没有geometricError

### ISSUE THREAD

**Issue by chaoslife** [fanvanzh/3dtiles#138]
你好，转为b3dm格式后，json文件内有缺失
JsonSerializationException: Required property 'geometricError' not found in JSON. Path '', line 1385, position 1.

3dtile.exe -f osgb -i C:\users\chaos\desktop\osgb -o c:\users\chaos\desktop\tile
INFO: 2020-06-01 09:32:27 - task over, cost 31.84 s.

**Comment by fanvanzh** [comment]
fix in b289fb0e43a582e8c80e364cefcbd87a097f74b1
