### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zwzhlj100000** [fanvanzh/3dtiles#145]
开发环境：VS2015 企业版  update3
操作系统：win7 64位
操作步骤：打开 vs/vs.sln，  debug + X64，删除了预先生成事件，然后进行编译，编译失败，错误信息如下：

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2065	“sence”: 未声明的标识符	vs	e:\conventor\fastest\src\master\ce3dtiles\src\osgb23dtile.cpp	859	

![image](https://user-images.githubusercontent.com/6670216/86073530-88ca6080-bab6-11ea-9cab-4e4416ff9da9.png)

**Comment by fanvanzh** [comment]
为什么 删除预先生成事件？ 
请阅读 **如何编译**
