### ISSUE TITLE
请问可以提供基于linux的二进制包吗

### ISSUE THREAD

**Issue by ali322** [fanvanzh/3dtiles#146]
方便做持续集成,谢谢

**Comment by fanvanzh** [comment]
linux 版本众多，比较难提供二进制包。
不过本项目代码都是跨平台的，自己编译也比较简单。
你可以参考 #29 , #42  来编译 linux 平台版本。

**Comment by fanvanzh** [comment]
支持了，阉割了 shpfile 和 gdal 库。

https://github.com/fanvanzh/3dtiles/wiki/How-to-build#linux-%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E

**Comment by ali322** [comment]
666
