### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by Chirag19** [fanvanzh/3dtiles#148]
Please guide I have following error 

Compiling serde-xml-rs v0.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
warning: unused import: `Serialize`
  --> src\main.rs:17:13
   |
17 | use serde::{Serialize, Deserialize};
   |             ^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0505]: cannot move out of `metadata.SRS` because it is borrowed
   --> src\main.rs:322:37
    |
242 |                     let v: Vec<&str> = metadata.SRS.split(":").collect();
    |                                        ------------ borrow of `metadata.SRS` occurs here
...
322 |                                 let wkt: String = metadata.SRS;
    |                                     ^^^ move out of `metadata.SRS` occurs here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0505`.
error: Could not compile `_3dtile`.

To learn more, run the command again with --verbose.

C:\Final\3dtiles_all\3dtiles>set RUSTUP_DIST_SERVER=http://mirrors.ustc.edu.cn/rust-static

C:\Final\3dtiles_all\3dtiles>set RUSTUP_UPDATE_ROOT=http://mirrors.ustc.edu.cn/rust-static/rustup

C:\Final\3dtiles_all\3dtiles>cargo build --release
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
   Compiling _3dtile v0.1.0 (C:\Final\3dtiles_all\3dtiles)
warning: unused import: `Serialize`
  --> src\main.rs:17:13
   |
17 | use serde::{Serialize, Deserialize};
   |             ^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0505]: cannot move out of `metadata.SRS` because it is borrowed
   --> src\main.rs:322:37
    |
242 |                     let v: Vec<&str> = metadata.SRS.split(":").collect();
    |                                        ------------ borrow of `metadata.SRS` occurs here
...
322 |                                 let wkt: String = metadata.SRS;
    |                                     ^^^ move out of `metadata.SRS` occurs here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0505`.
error: Could not compile `_3dtile`.

To learn more, run the command again with --verbose.

**Comment by fanvanzh** [comment]
please check your rustc version： 
`rustc -V`

maybe rust`s update caused this problerm.

**Comment by fanvanzh** [comment]
I build this project on appveyor ci platform, 
rust version is  rust-nightly-x86_64-pc-windows-msvc.
I did not meet this problerm, the build result is success.

**Comment by fanvanzh** [comment]
this is the build log：

https://ci.appveyor.com/project/fanvanzh/3dtiles
