### ISSUE TITLE
Windows Server  2012 R2 Datacenter 中直接使用预编译版 提示 not support now

### ISSUE THREAD

**Issue by PurityChan** [fanvanzh/3dtiles#149]
Windows Server  2012 R2 Datacenter 中直接使用预编译版 提示 not support now
![image](https://user-images.githubusercontent.com/8343216/87913592-eba18d00-caa1-11ea-8063-8e5d426dbec9.png)

**Comment by fanvanzh** [comment]
命令写错了，应该是：
`3dtile.exe -f osgb -i`

**Comment by PurityChan** [comment]
ok。参数写错了 =。=
