### ISSUE TITLE
切了一个多小时，进程没动静了，也没报错

### ISSUE THREAD

**Issue by PurityChan** [fanvanzh/3dtiles#150]
![image](https://user-images.githubusercontent.com/8343216/88008637-4c34d680-cb43-11ea-91cd-9f176317defd.png)

第一次Windows Server 2012 R2 切了一个多小时，一开始进程CPU保持70%+，原始OSGB数据总计40G+，指定目录中有输出结果（b3dm），总计30G+，不过没有json文件生成，感觉没切完，然后3dtile.exe进程CPU就一直0了，内存88M，控制台中一直没有任何输出结果。
之前在自己电脑win10中都很好，有个开始、结束时间，现在连开始时间都没有，跟硬件有关吗？还是我继续等待。。
我等不及后，直接关闭了控制台，然后删除了没切好的数据，重新执行同样的操作，控制台终于有了输出，如下
![image](https://user-images.githubusercontent.com/8343216/88009365-e8aba880-cb44-11ea-8b8b-4d00fddbefac.png)

我现在依然继续等待嘛

**Comment by PurityChan** [comment]
![image](https://user-images.githubusercontent.com/8343216/88012647-04b34800-cb4d-11ea-9a41-6b161cbcaf94.png)

1个小时后，我看到json生成了。然后ctrl+c退出指令，才会出来task over。指令本身不会自动退出，这是bug嘛

**Comment by fanvanzh** [comment]
用一个小一点的数据试试呢？

**Comment by PurityChan** [comment]
最后一次的数据是6G的，控制台出现了第一个INFO信息，第二个结束的INFO一直没出来，我人工CTRL+C退出指令才出来的，指令没有自动退出，我在WIN10中切这个6G的数据很完美。

不会自动退出、没有结束信息很苦恼啊，要自己检测tileset.json存不存在判断是否完成了

**Comment by fanvanzh** [comment]
按理说不应该啊，不过我也没环境。
你可以编译代码，加点 log 定位下问题吗？ 
看看这句代码是不是执行卡住了。
https://github.com/fanvanzh/3dtiles/blob/69621ac2496800ed85e0d859d15ce5c082811c4a/src/main.rs#L367
