### ISSUE TITLE
带佬，osgb格式的规范上哪儿能找到啊

### ISSUE THREAD

**Issue by onsummer** [fanvanzh/3dtiles#151]
是osg的开发文档里才有吗？
现在对gltf规范比较熟悉，但是始终找不到osgb格式的说明书，不太好转

**Comment by fanvanzh** [comment]
嗯，应该 osg 的开发文档里有

**Comment by onsummer** [comment]
那再提问一下，这个geometricError是随便写的吗？您在构造root瓦片时，几何误差的计算依据是啥？

**Comment by fanvanzh** [comment]
不是。 根据 tile 在某个比例是否足够小到可以舍弃来决定的。
你看看代码，我记得有 geometricError 计算的地方。
