### ISSUE TITLE
Need to project each vertex in OSGB file in order to place the Model to correct places

### ISSUE THREAD

**Issue by tom62291** [fanvanzh/3dtiles#154]
Hi , I find that it is need to project each vertex in OSGB file in order to place the model to correct location instead of just adding a single transform matrix in the root tileset.json.

Current flow is to convert the anchor point metadata.xml  to a transform matrix and place in root tileset.json.
However, I found that this way will fail if the model location is far from the anchor point.

In FME, each point will be projected when converting single OSGB file to 3D Tiles and I find that this way can make the model place in correct location.

Anyone can help to enhance this tools?

**Comment by fanvanzh** [comment]
If your module is far away from the original point, this project will not work correctly.
Because the earth is a spheroid，your module will above the earth's surface.

I think you should projected every vertex point/normal in function `osgb2glb_buf`.
