### ISSUE TITLE
KHR_techniques_webgl do not apply to normal

### ISSUE THREAD

**Issue by tom62291** [fanvanzh/3dtiles#155]
Hi, I have osgb files and converted to 3D tiles

However I find that the glb data in b3dm files have the problems which KHR_techniques_webgl do not apply to normal.

It is possible to fix it?

**Comment by fanvanzh** [comment]
3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{\"pbr\": true}"
