### ISSUE TITLE
vs文件里工程找不到源文件问题

### ISSUE THREAD

**Issue by darkfood** [fanvanzh/3dtiles#158]
打开vs文件里sln工程提示找不到源文件，这个该怎么解决？
![image](https://user-images.githubusercontent.com/22741601/97272729-4ac72880-186d-11eb-8aeb-f33492751474.png)

**Comment by fanvanzh** [comment]
配置下 头文件目录

**Comment by IKangXu** [comment]
@darkfood 
![image](https://user-images.githubusercontent.com/17905150/98494390-db433700-2277-11eb-9753-b66df4fbb7ed.png)
切换成x64即可

**Comment by darkfood** [comment]
谢谢，问题解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "IKangXu"<notifications@github.com&gt;; 
发送时间: 2020年11月9日(星期一) 上午10:40
收件人: "fanvanzh/3dtiles"<3dtiles@noreply.github.com&gt;; 
抄送: "swjtu黄贤喆"<1484472868@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [fanvanzh/3dtiles] vs文件里工程找不到源文件问题 (#158)





 
@darkfood
 
 切换成x64即可
