### ISSUE TITLE
显示有偏移

### ISSUE THREAD

**Issue by CharyPro** [fanvanzh/3dtiles#160]
请问，我的 metadata.xml 中的是2000坐标系，在代码中我也看到了做了84的坐标系转换，但是现在在cesium中显示依然有偏移，该解决这个问题？

![QQ截图20201111191943](https://user-images.githubusercontent.com/28482661/98805679-e9997a80-2452-11eb-9865-97dc65b102e0.png)

**Comment by fanvanzh** [comment]
你看看模型数据的坐标离中心点是不是很远。

**Comment by fanvanzh** [comment]
看上去 模型也没有贴到地面上，也可能是 cesium 视角问题。

**Comment by CharyPro** [comment]
我将模型贴到地面了，偏移还是很明显。您说的中心点是指什么？

**Comment by fanvanzh** [comment]
metadata.xml 里的 origin 坐标，对应到模型上的位置。
