### ISSUE TITLE
osg版本旧了，建立更新到最新版

### ISSUE THREAD

**Issue by hr0109** [fanvanzh/3dtiles#161]
超图合并根节点制作出来的osgb文件在3.6.5中是正常的，但是3.4.0打开会报错，建议把osg升级到最新版。

本来这点小问题应该可以自己解决的，但是这个项目用的rust，实在对rust的toolchain不熟悉，尝试替换bin/include/lib编译报错……

**Comment by fanvanzh** [comment]
3.4 升级到 3.6.5， 可能 头文件/函数 也有变动吧。

**Comment by fanvanzh** [comment]
检出 osg_3_65 分支试一下
