### ISSUE TITLE
shp转换的OGREnvelope超出范围该怎么做转换

### ISSUE THREAD

**Issue by HappyKuTou** [fanvanzh/3dtiles#163]
![image](https://user-images.githubusercontent.com/42768162/99498061-d4bc6a00-29b1-11eb-9903-306f9fdc17aa.png)
shp的OGREnvelope该如何转换为WGS-84标准

**Comment by HappyKuTou** [comment]
查了一下，当前版本只支持地理坐标系的shp转换，投影坐标系的shp需要先转换成地理坐标系。请问除了用arcgis这种软件，有算法可以做转换吗

**Comment by fanvanzh** [comment]
用 Arcgis 或者 QGis 转一下。
自己写代码的话，调用 proj4 这个库。

**Comment by HappyKuTou** [comment]
> 用 Arcgis 或者 QGis 转一下。
> 自己写代码的话，调用 proj4 这个库。
proj4转换有示例吗，找了好久没有找到

**Comment by fanvanzh** [comment]
https://proj.org/
可以参考下这个网站的文档
