### ISSUE TITLE
3dtiles get_geometric_error 函数理解

### ISSUE THREAD

**Issue by chinaminiren** [fanvanzh/3dtiles#165]
您好：
        首先，非常感谢您的开源。
 get_geometric_error 函数用于计算  geometric  error 。
请问这个实现的原理 ？为何  return  max_err / 20.0; ？？？
      非常感谢！

**Comment by onsummer** [comment]
几何误差我已研究透，可以参考我的博客，[3dTiles 几何误差详解](https://www.cnblogs.com/onsummer/p/13357226.html)

**Comment by chinaminiren** [comment]
> 几何误差我已研究透，可以参考我的博客，[3dTiles 几何误差详解](https://www.cnblogs.com/onsummer/p/13357226.html)

非常感谢
