### ISSUE TITLE
How to change "Box" bounding volume to "Region"

### ISSUE THREAD

**Issue by zhanwenxiao** [fanvanzh/3dtiles#166]
Hello, can u please help with it?
I see the source code, there are some code about "Region". But, I don't know how to create "Region" 3D tiles.
Thanks

**Comment by fanvanzh** [comment]
you can refer to this function: 
'write_tileset_region' in tileset.cpp

**Comment by zhanwenxiao** [comment]
OK! Thanks for replying. I have solved it.
