### ISSUE TITLE
win10下按照文档操作，遇到metadata.xml文件找不到的情况，多方尝试，未果，不知缘由，还请各位大佬不吝赐教。

### ISSUE THREAD

**Issue by hellomolike** [fanvanzh/3dtiles#167]
`ERROR: 2021-01-04 17:23:23 - D:\Data\Tile_+000_+000\metadata.xml is missing`
`ERROR: 2021-01-04 17:23:23 - dir D:\Data\Tile_+000_+000\Data not exist`

![image](https://user-images.githubusercontent.com/36214418/103520937-f070c680-4eb2-11eb-8a0c-60ea73f6cf26.png)

**Comment by fanvanzh** [comment]
’D:\Data\Tile_+000_+000\Data‘
这个目录是不是你 命令行 输入的？

**Comment by fanvanzh** [comment]
-i 输入数据的目录，osgb数据截止到 "\Data" 目录的上一级
