### ISSUE TITLE
shp 转3dtiles转换只出来第6级，而且在cesium里加载不出来

### ISSUE THREAD

**Issue by xduoo** [fanvanzh/3dtiles#168]
shp 转3dtiles转换只出来第6级，而且在cesium里加载不出来
3dtile.exe -f shape -c '{\"offset\":0,\"max_lvl\":20}' -i D:\data\shp\合肥.shp -o D:\data\floor\ --height Floor
[合肥.zip](https://github.com/fanvanzh/3dtiles/files/5924159/default.zip)

**Comment by fanvanzh** [comment]
坐标系是 4326 吗？

**Comment by xduoo** [comment]
是的 4326的

**Comment by xduoo** [comment]
> 坐标系是 4326 吗？

是的 4326的

**Comment by fanvanzh** [comment]
只有6级可能是因为 shp 文件本来就小，到第六层就不再分裂了。
加载不出来，你需要 DEBUG 以下 cesium 加载的流程看看是什么原因。

**Comment by xduoo** [comment]
> 只有6级可能是因为 shp 文件本来就小，到第六层就不再分裂了。
> 加载不出来，你需要 DEBUG 以下 cesium 加载的流程看看是什么原因。

好的 谢谢
