### ISSUE TITLE
下载下来，源码编译不了，未能找到项目“\vs\tile\tile.vcxproj

### ISSUE THREAD

**Issue by mrjjq** [fanvanzh/3dtiles#174]
缺少项目，编译不了

**Comment by fanvanzh** [comment]
用cargo build

**Comment by mrjjq** [comment]
那个预编译的可以用，不过，高程数据如何加载呢

**Comment by mrjjq** [comment]
cargo build：出现这个错误：
Caused by:
  process didn't exit successfully: `F:\迅雷下载\3dtiles-master\3dtiles-master\target\debug\build\_3dtile-afd3bbc831d633aa\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "E:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoF:\\迅雷下载\\3dtiles-master\\3dtiles-master\\target\\debug\\build\\_3dtile-18c1539678925f87\\out\\./src/osgb23dtile.o" "-c" "./src/osgb23dtile.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

**Comment by fanvanzh** [comment]
高程数据不用转 3dtile 了

**Comment by mrjjq** [comment]
请问高程数据如何处理，多谢

**Comment by fanvanzh** [comment]
别做伸手党
