### ISSUE TITLE
cargo build --relase 失败

### ISSUE THREAD

**Issue by lqzv** [fanvanzh/3dtiles#176]
我按照Wiki上的步骤编译，到cargo build -- release这一步时失败，提示

`error: failed to parse manifest at `D:\github\fanvanzh\3dtiles\Cargo.toml`

Caused by:
  the `registry.index` config value is no longer supported
  Use `[source]` replacement to alter the default index for crates.io.`

这个怎么解决呢？

**Comment by lqzv** [comment]
重复了，删除.cargo/config就好了

**Comment by fanvanzh** [comment]
谢谢， 我已经更新了 How to build 的 ReadME
