### ISSUE TITLE
介绍该软件的scoop桶的相关内容

### ISSUE THREAD

**Issue by sinloss** [fanvanzh/3dtiles#177]
您好！

非常感谢您的这款软件，它真的很赞，没有之一！我是一个scoop用户，我会将适合加入scoop桶的软件，都加入到[scoopcn](https://github.com/scoopcn/scoopcn)这个桶中，比如这款3dtile。在加入了`scoopcn`桶之后，谁都可以方便地用命令行
```
scoop install 3dtile
```
来安装，然后使用这个软件。

不知道我能否有机会将这个安装选项加入到该软件的`README.md`中。我认为这样可以帮助大家更快、更方便地安装、更新和使用这款软件。

**注**: 
在 [新加入的3dtile](https://github.com/scoopcn/scoopcn/commit/2585e3214d8814c9661b21f7760b7f189e165255) 中，我选择了使本库 *fanvanzh/3dtiles* 的`tag`作为版本更新的依据，然后以`README.md`上面所描述的 [Windows pre-build / 预编译下载](https://ci.appveyor.com/api/projects/fanvanzh/3dtiles/artifacts/3dtiles.zip?branch=master) 作为软件下载的路径。如果所述更新下载策略不符合实际情况，告诉我我就改。

**Comment by fanvanzh** [comment]
欢迎引用， scoop 是个不错的项目

**Comment by sinloss** [comment]
Close as per #179
