### ISSUE TITLE
Release版生成的b3dm的维度坐标疑问，以及编译失败

### ISSUE THREAD

**Issue by git4wht** [fanvanzh/3dtiles#18]
使用预编译的release版生成的版b3dm在表示是，感觉维度被对称调换了，即上下颠倒了。
使用最新的checkout编译失败。
编译环境：Win10_64+VS2015

**Comment by git4wht** [comment]
错误log
----
warning: unused import: `std::fs`
 --> build.rs:2:5
  |
2 | use std::fs;
  |     ^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

   Compiling log v0.3.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling aho-corasick v0.6.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
error: failed to run custom build command for `3dtile v0.1.0 (file:///H:/Map/workspace/3dtiles)`
process didn't exit successfully: `H:\Map\workspace\3dtiles\target\release\build\3dtile-c61bd21b20bea509\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "D:\\Tool\\VS\\VS2015\\VC\\BIN\\amd64\\cl.exe" "/nologo" "/MD" "/O2" "/I" "./src" "/I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "/DWIN32" "/FoH:\\Map\\workspace\\3dtiles\\target\\release\\build\\3dtile-3a25407e9c09e7ef\\out\\./src\\shp23dtile.o" "/c" "./src/shp23dtile.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

', H:\Map\tools\cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\cc-1.0.15\src\lib.rs:2158:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:576
   6: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:537
   7: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   8: cc::Tool::to_command
   9: cc::Build::compile
  10: <unknown>
  11: <alloc::arc::Arc<T>>::drop_slow
  12: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  13: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:479
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  15: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:458
  16: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:358
  17: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  18: main
  19: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  20: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  21: BaseThreadInitThunk
  22: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by fanvanzh** [comment]
参见
[编译指南](https://github.com/fanvanzh/3dtiles/wiki/How-to-build)

1、是否是 git clone的
2、vs2015 是不是 update3 的，由于代码里使用了部分 c++11， update3 才完全支持。

**Comment by git4wht** [comment]
我的环境是满足条件的，但是log中出现了【C:\projects\rust\src\libstd\】【f:\dd\vctools\crt\vcstartup\】是在我的机器上不存在的路径，这点很奇怪。

**Comment by fanvanzh** [comment]
这是编译器的源码目录
