### ISSUE TITLE
obj to b3dm?

### ISSUE THREAD

**Issue by Ggs1mida** [fanvanzh/3dtiles#180]
嗨楼主，obj可以转gltf，不知道现在能不能进行obj转b3dm的操作，或者gltf转b3dm？
感谢！

**Comment by fanvanzh** [comment]
gltf 转 b3dm 很简单，套个文件头就可以了。

**Comment by Ggs1mida** [comment]
@fanvanzh 才发现，哈哈，感谢感谢！

**Comment by zuixiaosanlang** [comment]
@fanvanzh @Ggs1mida 大佬怎么转呀
