### ISSUE TITLE
能否考虑支持linux上部署？如果需要在linux上编译要如何做？

### ISSUE THREAD

**Issue by szwilliam** [fanvanzh/3dtiles#181]
能否考虑支持linux上部署？如果需要在linux上编译要如何做？

**Comment by fanvanzh** [comment]
参考 #42

**Comment by fanvanzh** [comment]
I built one on ubuntu 20.04 base https://github.com/arcplus/3dtiles I changed the binary to fast3dtile and now working on github action for build.

I'll merge the main repo and create PR when I done. Download Link: https://github.com/chenzaichun/3dtiles/releases/download/test-build-on-ubuntu/fast3dtile.tar.gz

**Comment by fanvanzh** [comment]
refer from
https://github.com/fanvanzh/3dtiles/issues/29#issuecomment-658638116

**Comment by szwilliam** [comment]
Thanks,I will try.

**Comment by szwilliam** [comment]
After using the tar command, what should I do next and how to start the service？

**Comment by szwilliam** [comment]
> refer from
> [#29 (comment)](https://github.com/fanvanzh/3dtiles/issues/29#issuecomment-658638116)



> I built one on ubuntu 20.04 base https://github.com/arcplus/3dtiles I changed the binary to fast3dtile and now working on github action for build.
> 
> I'll merge the main repo and create PR when I done. Download Link: https://github.com/chenzaichun/3dtiles/releases/download/test-build-on-ubuntu/fast3dtile.tar.gz

在linux中解压后，如何将fast3dtile.tar.gz变成服务或者在linux中调用？

**Comment by fanvanzh** [comment]
你问得太多了

**Comment by szwilliam** [comment]
学习下

**Comment by szwilliam** [comment]
### ****

**Comment by szwilliam** [comment]
![image](https://user-images.githubusercontent.com/20187969/121158027-9ff3ff80-c87c-11eb-9f8d-02b01405962c.png)
在centos上，可以转换出来，但报了一个srs的错误，大佬有没有办法解决？

**Comment by szwilliam** [comment]
> ![image](https://user-images.githubusercontent.com/20187969/121158027-9ff3ff80-c87c-11eb-9f8d-02b01405962c.png)
> 在centos上，可以转换出来，但报了一个srs的错误，大佬有没有办法解决？会不会是proj4的版本问题。一个G的osgb转了10分钟。是不是慢？

对应的环境变量也设置了。  anyone can help me?

**Comment by fanvanzh** [comment]
1、设置 GDAL_PATH 的路径
2、确认下 GDAL_PATH 路径下 是否有 gcs.csv 文件
3、先设置环境变量，再 执行  ./3dtile

**Comment by fanvanzh** [comment]
你的测试机器是 几核的 CPU？

**Comment by fanvanzh** [comment]
支持了，阉割了 shpfile 和 gdal 库。

https://github.com/fanvanzh/3dtiles/wiki/How-to-build#linux-%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E
