### ISSUE TITLE
osgb转3d tile格式后，加载json报错：TypeError: t.scenes is undefined

### ISSUE THREAD

**Issue by StarDust0814** [fanvanzh/3dtiles#186]
![图片](https://user-images.githubusercontent.com/42524932/123585826-6b89b880-d816-11eb-91c1-1a8c2dcc218f.png)
**我用的cesium版本是1.82，使用工具将osgb转换为3dtile，转换过程中没有报错。但加载得到的json文件时出现上图错误
加载demo的部分代码如下**
![图片](https://user-images.githubusercontent.com/42524932/123586337-23b76100-d817-11eb-89cc-b8f198ecb2e8.png)

**Comment by onsummer** [comment]
Cesium 核心在 1.82 已经将 glTF 的解析拆分重写，要么等数据生产工具更新，要么自己debug提交错误，要么静等官方解决。

**Comment by onsummer** [comment]
已破案，不要使用 1.82 版本即可。

**Comment by fanvanzh** [comment]
fixed in 7f0f8af86a0abc3cf915862c1ad81a79b5217b02 by @onsummer
