### ISSUE TITLE
导出的b3dm是一个片上的建筑，还能够以一个建筑为单位导出吗？

### ISSUE THREAD

**Issue by git4wht** [fanvanzh/3dtiles#19]

**Comment by fanvanzh** [comment]
不明白。
是 osgb 数据，还是 shapefile 数据？

**Comment by git4wht** [comment]
将shapefile的数据，或者osgb 数据都行；
导出以建筑为单位就好进一步做各种丰富的处理了

**Comment by fanvanzh** [comment]
shapefile 是以整个 shapefile 作为一个场景的。
导出的是 一个范围，不是一个 建筑物

**Comment by libofei2004** [comment]
请问shapefile的三维场景是通用的格式吗，这方便的资料哪里有？

**Comment by fanvanzh** [comment]
@libofei2004 没啥资料，只有 3dtiles 的官方说明。 shapefile 转 3dtiles 自己研究实现的。

**Comment by libofei2004** [comment]
@fanvanzh 这种shapefile 的组织格式是什么样的呢，哪里在用这种格式描述三维模型？

**Comment by fanvanzh** [comment]
shapefile 是二维、三维矢量都可以。 shapefile 是 ERSI 的矢量文件格式。

**Comment by libofei2004** [comment]
我知道，但是shape格式通常不用来存储三维数据，应该没有通用的存储规则，所以你这里存三维数据的规则是什么？

**Comment by fanvanzh** [comment]
@libofei2004 普通的建筑轮廓面数据就可以，高度字段在属性里指定。（二维的）

**Comment by libofei2004** [comment]
你有样例可以试用下吗

**Comment by fanvanzh** [comment]
有。https://pan.baidu.com/s/1Gs578URBVO4N6qrX50JuPA

**Comment by libofei2004** [comment]
好，我试试。那这个格式属于你自定义的吧

**Comment by libofei2004** [comment]
目前这种建筑物轮廓面数据的描述方式是通用的吗
