### ISSUE TITLE
更新osg库问题

### ISSUE THREAD

**Issue by lixiaofdff** [fanvanzh/3dtiles#195]
您好，我想更新一下OSG库，把3.6.5版本osg的bin、lib、include替换之后再编译，只有verbose可以成功，release就会报link的错误
![image](https://user-images.githubusercontent.com/62696562/124852429-e1401200-dfd6-11eb-8e53-0fabb3b7dc4c.png)
请问该怎么办啊？ 我想转换fbx格式，这个版本的好像读不进去osgDB::readNodeFiles，返回了个空指针
求助大佬，感谢！

**Comment by fanvanzh** [comment]
link 报啥错误？在 vs command 里单独执行下 link 命令呢？
或者你用百度云盘共享下你的 3.6.5 osg 库，我周末时间编译下试试。
读 FBX 需要 osg-fbx plugin

**Comment by lixiaofdff** [comment]
好的，我的3.6.5osg库是官网release版本，osg-fbx plugin找到两个，FBX SDK和osgFBX
c++还是不太熟，搞的有点头大，感谢大佬指点！
网盘链接：
链接：https://pan.baidu.com/s/1PFakAXkLoWzqZ2A3-Kh9vg 
提取码：qr7a

**Comment by fanvanzh** [comment]
你可以新建个 c++ 工程， 把 osg23dtile.cpp 拉过去。
我试了下，是新版本的osg库很多函数link不上。
例如:
```
osgb23dtile.obj : error LNK2001: 
无法解析的外部符号 "__declspec(dllimport) public: static class osgDB::Registry * __cdecl osgDB::Registry::instance(bool)" (__imp_?instance@Registry@osgDB@@SAPEAV12@_N@Z)
```

等 osgb23dtile.cpp 可以成功编译了，再来用 cargo build 编译 rust 这个项目。

**Comment by fanvanzh** [comment]
或者你  cargo clean 之后再 cargo build 试试

**Comment by fanvanzh** [comment]
我推了一个 osg_3_65 的分支，你 checkout 下来试试看；

先 cargo clean 再  cargo build
