### ISSUE TITLE
linux环境下支持转换吗

### ISSUE THREAD

**Issue by h2936817294** [fanvanzh/3dtiles#196]

**Comment by fanvanzh** [comment]
支持， 在 issues 里搜索下 linux、ubuntu 等关键字

**Comment by h2936817294** [comment]
小白，对这个不太懂，环境是centos，现在在cargo build --release这一步报错
![image](https://user-images.githubusercontent.com/56542531/125572720-dc380541-dae1-4aec-9228-bc5d39746d4a.png)
![image](https://user-images.githubusercontent.com/56542531/125572756-1561361d-11f6-45af-8ad2-040cb6464947.png)

**Comment by h2936817294** [comment]
用的是这个分支下的代码，https://github.com/arcplus/3dtiles，
不太懂还需要改些什么

**Comment by fanvanzh** [comment]
so 版本不匹配，自行解决 gdal.so 和 osg.so 。
因为 linux 版本众多，不好提供预编译好的库文件。

**Comment by fanvanzh** [comment]
支持了，阉割了 shpfile 和 gdal 库。

https://github.com/fanvanzh/3dtiles/wiki/How-to-build#linux-%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E

**Comment by h2936817294** [comment]
非常感谢！现在已经可以编译成功了

**Comment by h2936817294** [comment]
![image](https://user-images.githubusercontent.com/56542531/125631972-0e730f0c-608c-4a9a-8faf-21cd0e3770c3.png)
转换会失败，报段错误，具体是哪里的原因没有找到

**Comment by fanvanzh** [comment]
编译个 debug 版本。
cargo build --debug
用 gdb 调试下看看 挂在哪儿了

**Comment by h2936817294** [comment]
![image](https://user-images.githubusercontent.com/56542531/125777506-01996393-c871-4e42-bd5d-bcc7c5c65aa7.png)
报错只有一点点，好像是libosgDB.so.130这个文件的问题

**Comment by fanvanzh** [comment]
估计是 缺少 osgPlugins
你在linux上 源码编译一遍 osg，把依赖库都带上。
成功了帮 提个 PR 合入一下

**Comment by h2936817294** [comment]
换了好几个osg的lib，没成功

**Comment by fanvanzh** [comment]
你需要编译一份 osgPlugins-3.6，然后放到 libosg.so 同级目录

**Comment by m78coder** [comment]
osgPlugins是这个仓库（https://github.com/openscenegraph/OpenSceneGraph）的吗

**Comment by fanvanzh** [comment]
参考 How to build / Linux 的说明
