### ISSUE TITLE
添加Proj4库，自动解析倾斜模型元数据文件，自动转换模型中心坐标

### ISSUE THREAD

**Issue by zwzhlj100000** [fanvanzh/3dtiles#197]
添加Proj4库，自动解析倾斜模型元数据文件，自动转换模型中心坐标

**Comment by 714865387** [comment]
请问，您这个更新是为了解决什么问题

**Comment by fanvanzh** [comment]
现在已经有 
解析倾斜模型元数据文件，自动转换模型中心坐标
这个功能了。

**Comment by 714865387** [comment]
我也看到更新了，但是我刚才下载最新代码编了一个版本转出来的倾斜摄影完全是乱的，所以很纠结。要不老大给我提供个编译后版本我在试试，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanvanzh/3dtiles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午3:39
***@***.***&gt;;
抄送:&nbsp;"Ｓmilｅ  ☀☀    ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanvanzh/3dtiles] 添加Proj4库，自动解析倾斜模型元数据文件，自动转换模型中心坐标 (#197)





 
现在已经有
 解析倾斜模型元数据文件，自动转换模型中心坐标
 这个功能了。
