### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by wuvalue** [fanvanzh/3dtiles#198]
The following warnings were emitted during compilation:

warning: cl: ������ warning D9035 :��Gm��ѡ���ѷ���������ڽ����İ汾���Ƴ�
warning: cl: ������ warning D9035 :��Gm��ѡ���ѷ���������ڽ����İ汾���Ƴ�
warning: cl: ������ warning D9035 :��Gm��ѡ���ѷ���������ڽ����İ汾���Ƴ�

error: failed to run custom build command for `_3dtile v0.1.0 (......\Desktop\3dtiles\3dtiles-master)`

Caused by:
  process didn't exit successfully: `C:\Users\wu\Desktop\3dtiles\3dtiles-master\target\release\build\_3dtile-24fb515e0eb35575\build-script-build` (exit code: 1)
  --- stderr

  error occurred: Command "D:\\VS2019\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "./src" "-I" "./src/osg" "-Zi" "-Gm" "-INCREMENTAL" "-DWIN32" "-D_WINDOWS" "-FoC:\\Users\\wu\\Desktop\\3dtiles\\3dtiles-master\\target\\release\\build\\_3dtile-e2284d4fa59c54b6\\out\\./src/osgb23dtile.o" "-c" "./src/osgb23dtile.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

warning: build failed, waiting for other jobs to finish...

**Comment by fanvanzh** [comment]
可能是中文注释的问题， 用 vs 目录的sln 编译一下试试

**Comment by wuvalue** [comment]
尝试用VS2019 debug报错。
错误	C2065	“baseColorTexture”: 未声明的标识符
错误	C2065	“sence”: 未声明的标识符
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int

**Comment by wuvalue** [comment]
尝试用VS2019 debug报错。
错误 C2065 “baseColorTexture”: 未声明的标识符
错误 C2065 “sence”: 未声明的标识符
错误 C4430 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
@fanvanzh

**Comment by fanvanzh** [comment]
> 尝试用VS2019 debug报错。
> 错误 C2065 “baseColorTexture”: 未声明的标识符
> 错误 C2065 “sence”: 未声明的标识符
> 错误 C4430 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
> @fanvanzh

那就是中文注释的问题，把中文注释都删了吧

**Comment by wuvalue** [comment]
> > 尝试用VS2019 debug报错。
> > 错误 C2065 “baseColorTexture”: 未声明的标识符
> > 错误 C2065 “sence”: 未声明的标识符
> > 错误 C4430 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
> > @fanvanzh
> 
> 那就是中文注释的问题，把中文注释都删了吧

谢谢，可以了，这个对坐标有要求嘛，还是只支持WGS84

**Comment by fanvanzh** [comment]
没有要求，会自动转

**Comment by fanvanzh** [comment]
fix in commit d540b5d136721fdf6df3c4437b5b7cadccdfd5d4
