### ISSUE TITLE
Why can not build on ubantu?  Do I lose some package?

### ISSUE THREAD

**Issue by mty0716** [fanvanzh/3dtiles#199]
Would you help ? Thank you please.

This is my error issue:

warning: unused import: `Serialize`
  --> src/main.rs:17:13
   |
17 | use serde::{Serialize, Deserialize};
   |             ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
   --> src/main.rs:369:24
    |
369 |         error!("{}", e.description());
    |                        ^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
  --> src/fun_c.rs:16:40
   |
16 |                         error!("{}", e.description());
   |                                        ^^^^^^^^^^^

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
  --> src/fun_c.rs:40:36
   |
40 |                     error!("{}", e.description());
   |                                    ^^^^^^^^^^^

warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
  --> src/fun_c.rs:45:32
   |
45 |                 error!("{}", e.description());
   |                                ^^^^^^^^^^^

warning: this method call currently resolves to `<&[T; N] as IntoIterator>::into_iter` (due to autoref coercions), but that might change in the future when `IntoIterator` impls for arrays are added.
  --> src/shape.rs:78:33
   |
78 |             for &x in [2, 3, 5].into_iter() {
   |                                 ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
   |
   = note: `#[warn(array_into_iter)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #66145 <https://github.com/rust-lang/rust/issues/66145>

error: linking with `cc` failed: exit status: 1

...
...
...

error: aborting due to previous error; 6 warnings emitted

error: could not compile `_3dtile`

**Comment by mty0716** [comment]
And I just want to use the function 'shapefile to 3dtiles', can I only extract this module？

**Comment by fanvanzh** [comment]
A1: your code seem not to be the latest version.

A2: yes, you can compile the shp23dtile.cpp using g++.
