### ISSUE TITLE
停止工作

### ISSUE THREAD

**Issue by z3214965** [fanvanzh/3dtiles#2]
你好：
当使用3dtiles.exe，osgb->3dtitles,，exe会停止工作
![2018-03-12_135044](https://user-images.githubusercontent.com/18589356/37267912-14379818-25fe-11e8-8be6-d515f972fe66.png)
麻烦你帮我分析下，谢谢！

**Comment by fanvanzh** [comment]
请将 操作系统版本、机器配置、编译器版本 告诉我。
你会使用 vs2015 吗？
打开 vs2015 ，可以附件到进程调试。
1、编译 debug 版本程序： 
`cargo build`
2、运行程序，然后 在VS2015 -> 调试 -> 附加到进程 -> 找到3dtile.exe 
3、定位出错的位置和代码

**Comment by z3214965** [comment]
![error](https://user-images.githubusercontent.com/18589356/37318558-20d8037a-26a6-11e8-846f-9e47762a70b1.PNG)
![default](https://user-images.githubusercontent.com/18589356/37318570-2991d4dc-26a6-11e8-8a6e-c5037e7d6c4c.PNG)
win10、vs2017

**Comment by fanvanzh** [comment]
你会 c++ 吗？ 自己 debug 一下吧。
或者把 数据给我试试

**Comment by z3214965** [comment]
你帮我看看吧，百度网盘连接https://pan.baidu.com/s/10C1_qXuuwHP9qTPANR814w，谢谢！

**Comment by fanvanzh** [comment]
更新一下代码，并用 vs2015 编译环境

**Comment by z3214965** [comment]
ok!

**Comment by z3214965** [comment]
还是有个错误，根据转换的文件个数，应该是这个文件GWH\Data\Tile_+001_+001\Tile_+001_+001_L23_0001002100.osgb
![error](https://user-images.githubusercontent.com/18589356/37389262-9560a640-279e-11e8-9746-204be285b2c4.PNG)

**Comment by fanvanzh** [comment]
再拉一次，我刚又提交了

**Comment by z3214965** [comment]
转换的数据能用了，非常感谢！
但我这有个问题，三维平台开DEM后看不见3dtiles数据，关了就可以，不知道为什么

**Comment by fanvanzh** [comment]
DEM 有高度，盖住了你的模型。

**Comment by z3214965** [comment]
18801115287 我微信号，要是方便的话能不能加我下，咨询下关于rust方面的问题，以前从来没有用过

**Comment by zxr12748** [comment]
这个转换后的结果看起来没有pagedLOD？

**Comment by fanvanzh** [comment]
应该有 PageLOD， 可能 GeometricError 有误差

**Comment by z3214965** [comment]
我这还有两个问题，帮我看下，谢谢！
1、既然加DEM会有遮挡，转换的时候能不能加个高度，或则通过其他什么设置能能在不加DEM的情况下cesium上能贴地。
2、你平时开发和调试rust用什么工具。

**Comment by fanvanzh** [comment]
@z3214965 
1、可以。参数 offset:0 , 可以配置模型最低面贴地。另外也可以在 cesium 加载模型时候，改 js 代码指定高度。
2、开发用 idea + rust 插件， 调试用 windows 附加调试。
linux 开发调试，用 clion + rust 插件，开发调试一体。

**Comment by z3214965** [comment]
1、设置参数 offset:0是指当前您这个项目里？还是设置cesium某一个对象的属性？
2、cesium 加载模型时候，改 js 代码指定高度是指的哪个对象的哪个属性？我是用Cesium3DTileset加载数据的
3、如果调试用 windows 附加调试的话是不是只能查看程序是否有错误，而不能单步调试？
