### ISSUE TITLE
转出的3dtiles模型发黑

### ISSUE THREAD

**Issue by secretxu** [fanvanzh/3dtiles#20]
我用您的这个工具把osgb转成3dtiles格式之后，用cesium打开发现模型整体都发暗发黑，请问这个有没有办法解决？

**Comment by fanvanzh** [comment]
非常黑吗？
是 cesium 光照的影响吧。

**Comment by secretxu** [comment]
恩是的，这个问题已经解决了，是cesium的原因

**Comment by libofei2004** [comment]
我也发现过，用其他工具切出来的没有这个问题
