### ISSUE TITLE
转出来的模型加载到CesiumForUnreal中没有纹理材质

### ISSUE THREAD

**Issue by LaogaKAKA** [fanvanzh/3dtiles#204]
将osgb转成3DTiles，加载到虚幻引擎的Cesium插件中变成白模了，但web端加载没有问题

**Comment by fanvanzh** [comment]
估计是着色器材质的问题，使用 pbr材质 生成 3dtile。

3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{\"pbr\": true}"

**Comment by LaogaKAKA** [comment]
> 
> 
> 估计是着色器材质的问题，使用 pbr材质 生成 3dtile。
> 
> 3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{"pbr": true}"

确实是材质的问题，数据本身也有点问题，已经解决，非常感谢 : )

**Comment by fanvanzh** [comment]
已使用 KHR_materials_unlit 代替 KHR_technique_webgl 扩展

**Comment by xiasun** [comment]
666666，大佬要不要有空再发个release，或者readme里面提一句

**Comment by fanvanzh** [comment]
> 

我记得首页的 Prebuild 已经更新过了

**Comment by cloudinnng** [comment]
我也遇到该问题,已顺利解决,可以在readme加一句,unity或者unreal无纹理的解决方案,多谢

**Comment by ZZPokemon** [comment]
这个可能会解析失败 我这样使用就成功了：

 3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{\"pbr\": true}"


> 估计是着色器材质的问题，使用 pbr材质 生成 3dtile。
> 
> 3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{"pbr": true}"
