### ISSUE TITLE
在Ubuntu 上进行shp23dtiles转换出错

### ISSUE THREAD

**Issue by mty0716** [fanvanzh/3dtiles#205]
osg版本一定是固定的吗，还是最新版本不可以？
现在的osg是3.6.5 ，转换shp时报错为
./3dtiles/target/release/_3dtile -f shape -i ./input_data/jzw.shp -o ./out_data/ --height Height
ERROR: 2021-08-14 17:44:19 - convert shapefile failed

g++ shp23dtiles.cpp 时报错
undefined reference to `osg::BufferData::resizeGLObjectBuffers(unsigned int)'

**Comment by fanvanzh** [comment]
只有 branch_3_65 用的是 osg 3.6.5 
master 上没更新 osg 库版本

**Comment by gisspace** [comment]
ubuntu 那个系统可以build成功

**Comment by liaozd** [comment]
可否发布一个linux编译好的二进制文件？谢谢

**Comment by fanvanzh** [comment]
增加了 linux 系统的编译测试
