### ISSUE TITLE
转换后的3d tiles存在位置偏移

### ISSUE THREAD

**Issue by hechenglongfell** [fanvanzh/3dtiles#209]
范老师，你好：
      通过你这个转换工具，将osgb转为3d tiles时存在大概几十米的偏移误差。
我自己的用例数据为一个20GB的osgb数据，坐标系为：EPSG:4544，中心坐标：（643104,3493316,0）
我验证如下：
1.通过你提供的这个工具，转换后，在cesium中展示并叠加geojson格式的polygon,发现位置偏差：如：图1
2.为了验证是转换后的3d tiles存在偏移，还是polygon存在偏移，我在arcgis pro中叠加osgb和这个polygon，他们位置关系正确。如：图2
3.我借助cesiumlab工具转换osgb-->3d tiles,并在cesium中叠加展示，他们位置关系正确。如：图3
![图1](https://user-images.githubusercontent.com/13324419/137660549-5145d2da-fda4-48d3-bd78-a75f8db4f5d7.jpg)
![图2](https://user-images.githubusercontent.com/13324419/137660575-cd54a812-4c12-4e67-ae6b-ba91e26826df.jpg)
![图3](https://user-images.githubusercontent.com/13324419/137660597-ef6e6950-d233-410e-95fc-adf0276bfd89.jpg)
另，运行工具过程中，输出的wgs84中心坐标为：（106.50709895113127, 31.553389611480966）

**Comment by ax123sky** [comment]
我这边转换完成之后使用cesium加载也是有偏移，高度、经纬度偏移都有一些偏移。这个问题你解决了吗？

**Comment by hechenglongfell** [comment]
用的是cesiumlab转的3dtiles

**Comment by fanvanzh** [comment]
这个可能需要逐顶点对osgb进行proj4投影，现在是只处理了局部坐标系的原点。

**Comment by IKangXu** [comment]
> 这个可能需要逐顶点对osgb进行proj4投影，现在是只处理了局部坐标系的原点。

具体怎么实现，有思路吗

**Comment by IKangXu** [comment]
> > 这个可能需要逐顶点对osgb进行proj4投影，现在是只处理了局部坐标系的原点。
> 
> 具体怎么实现，有思路吗

已经解决。

**Comment by yipiaojun** [comment]
[Steelwall2014]君的 pull request 有效，点赞！

**Comment by fanvanzh** [comment]
fixed by #249
