### ISSUE TITLE
关于geometricError的问题

### ISSUE THREAD

**Issue by zhouyang1991** [fanvanzh/3dtiles#21]
成功转换后，geometricError并不是按层级递减，请问这是正常情况吗？用cesium显示也会在某个级别模型显示异常。
![tileset](https://user-images.githubusercontent.com/13848528/40116027-f69eb208-5944-11e8-9fb8-c8737d1332a4.png)
![image](https://user-images.githubusercontent.com/13848528/40116036-0397c166-5945-11e8-839a-395443f9e669.png)

**Comment by fanvanzh** [comment]
感谢你的反馈。
看上去 Data/Tile_+001_+000 这个根节点处理 GeometricError 时候有点问题。

**Comment by fanvanzh** [comment]
由于 Tile_+001_+000 这个节点没有指定层级，原来代码默认用的 15 级，现在改成了 10 级。
try again
