### ISSUE TITLE
osgb转glb后用cesium加载，模型发生旋转

### ISSUE THREAD

**Issue by longshaooo7** [fanvanzh/3dtiles#210]
这是转成glb后加载到cesium的模型，位置正确但不知道为什么模型发生了旋转（osgb是世界坐标系相对锚点的坐标）
![111](https://user-images.githubusercontent.com/4747305/139797065-bdf617e7-3365-4c5f-bb71-7e94d2d96ec3.jpg)

下面是我把生成的glb又转成了b3dm，然后写了个tileset用3dtile形式加载的，结果显示正常，我现在应该怎样才能直接加载glb模型也能正确显示呢
![222](https://user-images.githubusercontent.com/4747305/139773191-1b5ea03c-d856-4731-adcd-6fd38814097a.jpg)

**Comment by fanvanzh** [comment]
是 Y/Z 轴翻转了吗？

**Comment by fanvanzh** [comment]
fixed by #249
