### ISSUE TITLE
fatal error: osg/MatrixTemplate: No such file or directory

### ISSUE THREAD

**Issue by gisspace** [fanvanzh/3dtiles#211]
系统：Linux version 5.4.0-77-generic (buildd@lgw01-amd64-028) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
错误：
   Compiling xml-rs v0.3.6
The following warnings were emitted during compilation:

warning: In file included from ./src/osg/osg/Shader:25,
warning:                  from ./src/osg/osg/StateAttribute:20,
warning:                  from ./src/osg/osg/Material:18,
warning:                  from ./src/shp23dtile.cpp:10:
warning: ./src/osg/osg/GLExtensions:33:10: fatal error: osg/MatrixTemplate: No such file or directory
warning:    33 | #include <osg/MatrixTemplate>
warning:       |          ^~~~~~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `_3dtile v0.1.0 (/home/3dtiles/3dtiles)`

Caused by:
  process didn't exit successfully: `/home/3dtiles/3dtiles/target/release/build/_3dtile-3bd93cb2522ec516/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/3dtiles/3dtiles/target/release/build/_3dtile-0cb009fe500c30cb/out/./src/tileset.o" "-c" "./src/tileset.cpp"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/3dtiles/3dtiles/target/release/build/_3dtile-0cb009fe500c30cb/out/./src/shp23dtile.o" "-c" "./src/shp23dtile.cpp"
  cargo:warning=In file included from ./src/osg/osg/Shader:25,
  cargo:warning=                 from ./src/osg/osg/StateAttribute:20,
  cargo:warning=                 from ./src/osg/osg/Material:18,
  cargo:warning=                 from ./src/shp23dtile.cpp:10:
  cargo:warning=./src/osg/osg/GLExtensions:33:10: fatal error: osg/MatrixTemplate: No such file or directory
  cargo:warning=   33 | #include <osg/MatrixTemplate>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/3dtiles/3dtiles/target/release/build/_3dtile-0cb009fe500c30cb/out/./src/shp23dtile.o" "-c" "./src/shp23dtile.cpp" with args "c++" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by fanvanzh** [comment]
是用的 linux_osg_370 分支吗？

**Comment by gisspace** [comment]
是的，我使用这个版本在centos8.3上也没有通过

**Comment by fanvanzh** [comment]
已增加缺失的头文件

**Comment by gisspace** [comment]
好的，谢谢，我一会重新编译下

**Comment by gisspace** [comment]
系统：Linux version 5.4.0-77-generic (buildd@lgw01-amd64-028) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021

/usr/bin/ld: /home/3dtiles/tilt-3dtiles/target/release/build/_3dtile-0cb009fe500c30cb/out/lib_3dtile.a(osgb23dtile.o): in function `osgb2glb_buf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MeshInfo&)':
          osgb23dtile.cpp:(.text._Z12osgb2glb_bufNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS4_R8MeshInfo+0x134): undefined reference to `osgDB::readNodeFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osgDB::Options const*)'
          **collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)**

**Comment by fanvanzh** [comment]
找不到 libosg.so?
我提供的预编译 so 在 ./lib 目录, 编译器用的 4.8

**Comment by gisspace** [comment]
你好是否可以提供一份第三方依赖库名单 ，我用源码编译下，如果没问题，我到时可以合并上来。

**Comment by fanvanzh** [comment]
osg 和 gdal

**Comment by gisspace** [comment]
OS：Ubuntu20.04
编译后OSG和GDAL后配置环境变量：
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 
Compiling _3dtile v0.1.0 (/home/3dtiles/tilt-3dtiles)
    Finished release [optimized] target(s) in 9.26s
