### ISSUE TITLE
osgb转3dtiles，模型显示碎片

### ISSUE THREAD

**Issue by CharyPro** [fanvanzh/3dtiles#215]
您好，当我在使用该程序将osgb转为3dtiles后，在cesiumlab中打开模型显示碎片（如图一），使用cesiumlab转换的3dtiles后模型是正常的。我试了将该程序转换后的b3dm转为glb和将原始的一块osgb文件转为glb，在meshlab中查看也都是碎片（如图二）。

附件是那一块osgb文件，麻烦帮我看一下，谢谢

![3dtiles](https://user-images.githubusercontent.com/28482661/147212957-ae67759d-8909-408c-b774-2e70e9ce385f.png)
![glb](https://user-images.githubusercontent.com/28482661/147213036-18689bc8-cb9c-436c-a136-f4640df0d338.png)

**附件**：[osgb.zip](https://github.com/fanvanzh/3dtiles/files/7767913/osgb.zip)

**Comment by fanvanzh** [comment]
好像确实有问题

**Comment by CharyPro** [comment]
@fanvanzh 昨天我发现这个原因好像是因为使用的osgb文件中三角面顶点的顺序有的是 **TRIANGLE_STRIP**模式，有的是**TRIANGLES**模式，代码里面貌似只针对**TRIANGLES**这一种模式进行处理

**Comment by fanvanzh** [comment]
已修复， 但是在 meshlab 中查看效果还是不对，估计是 meshlab 对 TriangleStrip 支持不好。
在 gltf-viewer、blender 软件中查看，效果正常。

![image](https://user-images.githubusercontent.com/10379652/147730951-49a6cba4-0dd8-4119-8b87-4348ca5f550d.png)

**Comment by fanvanzh** [comment]
你可以在这个页面，下载最新 build 结果
https://github.com/fanvanzh/3dtiles/actions/runs/1636711784
