### ISSUE TITLE
osgb文件集可以转换成glb么？

### ISSUE THREAD

**Issue by YangShuqing** [fanvanzh/3dtiles#218]
需求：将osgb文件集转换为 glb
使用 命令 `3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path`  进行转换后得到的文件是.b3dm 
看文档中 `-f` 指定的是 输入文件的格式，如何指定输出文件的格式呢？

**Comment by fanvanzh** [comment]
-f gltf， 把支持的模型转为 gltf/glb
`3dtile.exe -f gltf -i E:\a.osgb -o E:\b.glb`

**Comment by YangShuqing** [comment]
@fanvanzh  试了下可以了，是只支持单个文件的转换么？看转换后的glb文件偏小，丢失很多细节，不像是整个文件集转换后的模型

**Comment by fanvanzh** [comment]
你是要把 目录下所有文件都转 glb 吗？ 那可以写个批处理
