### ISSUE TITLE
我在centos7.3上转换 提示坐标转换失败

### ISSUE THREAD

**Issue by andy-cd-g** [fanvanzh/3dtiles#219]
epsg convert failed!

只有坐标转换失败，文件是转换成功了的 osgb转3dtiles

**Comment by fanvanzh** [comment]
那可能加载到球上位置不对，你可以手动把 metadata.xml 里的坐标改成经纬度坐标

**Comment by andy-cd-g** [comment]
epsg convert failed!  这个是你打印的错误提示  不应该是 我那配置不对吗  windows下可以的  linux不行

**Comment by liwei0705** [comment]
确实有这个错误。Ubuntu18.04
./target/release/_3dtile --format osgb --input /mnt/d/workspace/osgbdata/KLN --output ./threedtiles222/

ERROR: 2022-11-30 06:27:38 - epsg convert failed!
INFO: 2022-11-30 06:28:01 - task over, cost 23.35 s.


应该是这段代码，osgb::epsg_convert返回false

                                    unsafe {
                                        use std::ffi::CString;
                                        let c_str = CString::new(gdal_data).unwrap();
                                        let ptr = c_str.as_ptr();
                                        if osgb::epsg_convert(srs, pt.as_mut_ptr(), ptr) {
                                            center_x = pt[0];
                                            center_y = pt[1];
                                            info!("epsg: x->{}, y->{}", pt[0], pt[1]);
                                        } else {
                                            error!("epsg convert failed!");
                                        }
                                    }

**Comment by fanvanzh** [comment]
应该是 linux 分支的代码， 屏蔽了 GDAL transform 的代码， 因为没配置 GDAL 依赖库

**Comment by fanvanzh** [comment]
应该可以， 你把代码里 宏开关去了

**Comment by liwei0705** [comment]
linxu分支里的DIFF不少...没找到要打开哪个开关...方便指点一下吗

**Comment by fanvanzh** [comment]
> 

#ifdef _WIN32
这个宏包起来的代码，只在 Windows 环境下生效，去掉这个宏，在 linux 也编译通过即可

**Comment by liwei0705** [comment]
谢谢，搞定了https://github.com/liwei0705/3dtiles/tree/linux_osg_370

简单memo了一下
https://github.com/liwei0705/3dtiles/blob/linux_osg_370/linux_README.md

**Comment by haodondon** [comment]
@liwei0705 ，可以提供一下编译后的库吗，我再centos7尝试编译你提供d的https://github.com/liwei0705/3dtiles/tree/linux_osg_370，
编译没问题，执行提示

ERROR: 2023-07-27 07:00:59 - epsg convert failed!
Segmentation fault

gdal：GDAL 1.11.4, released 2016/01/25

**Comment by LYP857** [comment]
@liwei0705 大哥你修改完的代码没有在仓库吗，我攒看起来和原作者的一样吖，tileset.cpp这个文件最后是什么样的呢，还有gdal版本有要求嘛？

**Comment by LYP857** [comment]
@liwei0705 大哥，或者能够给我一个编译后好的嘛，我尝试了多次，ubantu下就是编译不成功，去cenots编译成功但是却坐标错误

**Comment by liwei0705** [comment]
说明文档：https://github.com/fanvanzh/3dtiles/commit/599ded2c6b77fe29f9eca371baa1cdf787e465b4?diff=unified&w=1
tileset.cpp：
https://github.com/fanvanzh/3dtiles/blob/6f1ea3adaaf573e3d36cbc008f2f612a6f4e8873/src/tileset.cpp

**Comment by fanvanzh** [comment]
增加了 linux 版本的编译测试

**Comment by IKangXu** [comment]
@liwei0705 [#314](https://github.com/fanvanzh/3dtiles/issues/314）
可以帮忙测试一下这份数据吗
我使用你改好的编译处理完之后，坐标也是错误的
