### ISSUE TITLE
osb_3_65分支转换的3dtiles没有贴图

### ISSUE THREAD

**Issue by penGYu-QAQ** [fanvanzh/3dtiles#226]
因为兼容问题需要使用3.65版本库，但使用osb_3_65分支转换的3dtiles没有贴图显示，使用master分支转换的是正常有贴图的，请问这是什么原因呢？

**Comment by penGYu-QAQ** [comment]
![1](https://user-images.githubusercontent.com/55725430/172805872-667d27d5-2060-47ab-b775-5b74bfdcd091.png)

**Comment by fanvanzh** [comment]
osg_plugin 目录复制到 bin 目录了吗

**Comment by penGYu-QAQ** [comment]
> osg_plugin 目录复制到 bin 目录了吗
您好，bin目录下面是有osg_plugin的，编译出来的release文件夹中也是有的
![1](https://user-images.githubusercontent.com/55725430/172969508-d52201e0-0427-4baa-982b-a75723365fb5.png)

**Comment by penGYu-QAQ** [comment]
> osg_plugin 目录复制到 bin 目录了吗

您好，bin目录下面是有osg_plugin的，编译出来的release目录下也是有
![1](https://user-images.githubusercontent.com/55725430/172969797-6cdb5e02-3457-4cdf-ae05-ec45f719c1f0.png)
的

**Comment by penGYu-QAQ** [comment]
造成这个问题的原因已经找到了，是因为我这边的cesium设置了一些参数的问题，但现在还不清楚为什么这个参数会对osb3.6.5版本转换的3dtiles有影响

**Comment by fanvanzh** [comment]
设置了什么参数导致的，可以贴出来给其他人参考下

**Comment by penGYu-QAQ** [comment]
> 设置了什么参数导致的，可以贴出来给其他人参考下

因为需要写自定义着色器，需要把ExperimentalFeatures.enableModelExperimental设置为true来启用ModelExperimental接口，就出现这样的问题了，目前这两者间的冲突还没找到解决方法。

**Comment by penGYu-QAQ** [comment]
> 设置了什么参数导致的，可以贴出来给其他人参考下

因为需要写自定义着色器，需要把ExperimentalFeatures.enableModelExperimental设置为true来启用ModelExperimental接口，就出现这样的问题了。现在还没找到这两者冲突的原因和解决方法。

**Comment by fanvanzh** [comment]
你可以参考下这个commit fe04fb5ac99ceb4b76f732cceb3c9df434827cdf, 生成结果不再使用自定义着色器

**Comment by penGYu-QAQ** [comment]
> 你可以参考下这个commit [fe04fb5](https://github.com/fanvanzh/3dtiles/commit/fe04fb5ac99ceb4b76f732cceb3c9df434827cdf) , 生成结果不再使用自定义着色器

我按照你的方法替换成了KHR_materials_unlit，但转换出来的效果有些不太一样
上面的数据是替换KHR_materials_unlit后转换的
下面的是正常转换的效果
![1](https://user-images.githubusercontent.com/55725430/185025197-9d7fccc8-a8f1-4904-a543-c82d5ce1fcca.jpg)

**Comment by penGYu-QAQ** [comment]
> 你可以参考下这个commit [fe04fb5](https://github.com/fanvanzh/3dtiles/commit/fe04fb5ac99ceb4b76f732cceb3c9df434827cdf), 生成结果不再使用自定义着色器

谢谢 替换KHR_materials_unlit扩展后确实解决了一些其他问题  而之前的问题和cesium1.87更新了的自定义着色器接口产生冲突，在1.97之后的版本这个接口已经被移除替换了替换后就没有之前材质丢失的问题了。
