### ISSUE TITLE
linux版本编译中遇到的问题

### ISSUE THREAD

**Issue by yonggandeliuguang** [fanvanzh/3dtiles#228]
![image](https://user-images.githubusercontent.com/46475872/176121624-11b4dab0-87d4-4c00-a62b-e65216567bca.png)
对于新手的我来说，这一句话理解起来有点困难。是不是这样子：
1.执行cargo build --release只适用于centos7。
2.其它的linux系统需要自己pull "https://github.com/openscenegraph/OpenSceneGraph.git" and build

**Comment by fanvanzh** [comment]
增加了 Ubuntu/Centos 环境的测试
