### ISSUE TITLE
centos7下切片报错

### ISSUE THREAD

**Issue by yonggandeliuguang** [fanvanzh/3dtiles#229]
ERROR: 2022-07-01 11:20:07 - wkt convert failed!
Error reading file /root/00f4d004-1f54-4352-ad09-71333fe7b4e4/Data/Tile_000000/Tile_000000.osgb: read error (Could not find plugin to read objects from file "/root/00f4d004-1f54-4352-ad09-71333fe7b4e4/Data/Tile_000000/Tile_000000.osgb".)
ERROR: 2022-07-01 11:20:07 - read node files [/root/00f4d004-1f54-4352-ad09-71333fe7b4e4/Data/Tile_000000/Tile_000000.osgb] fail!
ERROR: 2022-07-01 11:20:07 - open file [/root/00f4d004-1f54-4352-ad09-71333fe7b4e4/Data/Tile_000000/Tile_000000.osgb] fail!
ERROR: 2022-07-01 11:20:07 - failed: /root/00f4d004-1f54-4352-ad09-71333fe7b4e4/Data/Tile_000000/Tile_000000.osgb

作者有空的时候可以帮我看看这个报错是什么原因吗

**Comment by yonggandeliuguang** [comment]
> 

暂时还没有解决，作者把代码去掉了，加上了话编译不通过，因为我对rust不熟悉，所以暂时不知道怎么改。你可以研究一下，看看有没有办法解决。
![image](https://user-images.githubusercontent.com/46475872/179125979-e953c8fe-95f0-449b-8b5a-d4da87167db3.png)

**Comment by fanvanzh** [comment]
需要自己在 linux 环境下源码编译个 GDAL， 然后打开这段 宏定义
