### ISSUE TITLE
转换成功但是不能显示在cesium中

### ISSUE THREAD

**Issue by JamieZAZA** [fanvanzh/3dtiles#23]
1、是处理完了只有一个总的tileset.json的json文件吗？
2、现有的可加载的文件用smart3d工程导出的的结构如下：
---
### 图1：
![image](https://user-images.githubusercontent.com/20792726/40473752-a607de10-5f6f-11e8-8a2e-72f63157c124.png)
### 图2：
![image](https://user-images.githubusercontent.com/20792726/40474034-7ddf3586-5f70-11e8-99ec-a58f51058fe5.png)
### 图3：
![image](https://user-images.githubusercontent.com/20792726/40474133-c73a3adc-5f70-11e8-97e8-63708dec87d1.png)
---

使用你的工具结构如下：
---
### 图1：
![8 3dt68 8 ziil j3gwg](https://user-images.githubusercontent.com/20792726/40473561-14a81200-5f6f-11e8-9dbc-8300c1981638.png)
### 图:2：
![z xv3f sfer2 1 k8g9 vo](https://user-images.githubusercontent.com/20792726/40473567-19514a38-5f6f-11e8-9c21-d23bc4a9ee7f.png)
### 图3：
![4j 1 a kmrhitxudp_5gi](https://user-images.githubusercontent.com/20792726/40473571-1b1927dc-5f6f-11e8-823e-a0f75febdad2.png)

---
不知道是不是结构上的差异，我的本意是将原有的osgb文件整体高度值向下偏移。求指导

**Comment by fanvanzh** [comment]
是的，全部场景只有一个 tileset.json。
整体高度偏移可以在命令参数里加 
```-c "{\"offset\":-100}"``` 来控制加载高度。

**Comment by JamieZAZA** [comment]
可是为什么cesium加载不出来呢
```
var _tileSets=new Cesium.Cesium3DTileset({
				url:_url, //json链接
				skipLevels:5,
				maximumMemoryUsage:1024,
				dynamicScreenSpaceError:true,
				maximumScreenSpaceError :maxScreenSpaceErr,
				maximumNumberOfLoadedTiles : maxNumbOfLoadedTiles,
			});
			window.tilesPrimitives.add(_tileSets);
```
