### ISSUE TITLE
linux下切片成功，但是坐标转换失败了ERROR: 2022-07-01 14:58:02 - wkt convert failed!

### ISSUE THREAD

**Issue by yonggandeliuguang** [fanvanzh/3dtiles#230]
ERROR: 2022-07-01 14:58:02 - wkt convert failed!
只有这个错误信息，
作者有空的时候可以看一下吗
windows下切片成功，并且坐标转换正常

**Comment by fanvanzh** [comment]
linux 环境吗？ linux 环境把 GDAL 屏蔽了，自己编译个 GDAL 库然后打开相关的代码

**Comment by yonggandeliuguang** [comment]
> linux 环境吗？ linux 环境把 GDAL 屏蔽了，自己编译个 GDAL 库然后打开相关的代码

我把代码代开后会报错，请问这个可以怎么解决？

warning: In file included from ./src/gdal/ogr_core.h:34:0,
warning:                  from ./src/gdal/ogr_srs_api.h:35,
warning:                  from ./src/gdal/ogr_spatialref.h:35,
warning:                  from ./src/tileset.cpp:1:
warning: ./src/gdal/cpl_port.h:147:22: fatal error: direct.h: No such file or directory
warning:  #  include <direct.h>
warning:                       ^
warning: compilation terminated.

**Comment by fanvanzh** [comment]
自己准备 gdal 库

**Comment by fanvanzh** [comment]
增加了 linux 环境的编译测试
