### ISSUE TITLE
转换错误

### ISSUE THREAD

**Issue by crystallipei** [fanvanzh/3dtiles#24]
使用windows预编译版本，1.5G时，数据转换正常，cesium显示正常，换个数据，数据量60G，数据转换出现错误，请问这是什么原因？
![img20180531101737](https://user-images.githubusercontent.com/30790651/40757743-94fb963c-64bc-11e8-8a3f-33140c13b838.jpg)

**Comment by fanvanzh** [comment]
这是个由于目录名不规范、或者切片box范围为空导致的。
可以截图你的数据目录吗？ Tile_-023_+008 下面的目录。
或者加我 QQ 远程下： 954157387

**Comment by fanvanzh** [comment]
此问题已修复，请拉取最新版本
