### ISSUE TITLE
修改C++源码后，再次执行cargo build，没有生成新的.exe文件

### ISSUE THREAD

**Issue by moxuanzhu** [fanvanzh/3dtiles#246]
修改C++源码后，再次执行cargo build，没有生成新的.exe文件，该如何解决呢

**Comment by yipiaojun** [comment]
可以删了 target 下的内容后，重新生成

**Comment by moxuanzhu** [comment]
@yipiaojun 确实可以这么做，或则 cargo clear;再cargo build，但是开发调试效率好低啊，cargo build时间较长。

**Comment by fanvanzh** [comment]
更新下 build.rs 再编译试试，这是因为 C++ 代码是通过 build.rs 引入的，不是 cargo 原生管理的。

**Comment by fanvanzh** [comment]
参考主页 Build
