### ISSUE TITLE
生成的瓦片效果不是太理想，这是什么原因？

### ISSUE THREAD

**Issue by libofei2004** [fanvanzh/3dtiles#25]
同样的osgb数据，我用你的工具生成的模型感觉精细度不是很高，我用另一个工具生成的效果比这个要好的多，不知是什么原因？模型效果见https://pan.baidu.com/s/1WJJ-d8v6qDeyvRxiYzVYsw
里面“1_”开头的就是你的工具生成的模型，“2_”开头的就是其他工具生成的，效果对比还是挺明显的。

**Comment by fanvanzh** [comment]
感谢您的关注。
精度是在 tileset.json 里 GeometricError 控制的，为了加载流畅，误差控制的比较大，但是放大到最后一级是一样的。

**Comment by fanvanzh** [comment]
没有参数，可以自己修改 tileset.json 文件。

**Comment by libofei2004** [comment]
好的，另外亮度也偏低，这个可以修改吗

**Comment by fanvanzh** [comment]
高度需要修改 transform 矩阵的值。
你可以通过 -c 参数指定模型到地面高度。
也可以在 cesium 加载时候指定。

**Comment by libofei2004** [comment]
高度明白，我是问亮度，模型看上去偏暗

**Comment by fanvanzh** [comment]
@libofei2004 感谢你的意见。

**Comment by libofei2004** [comment]
和你共同学习研究，随时关注你进度

**Comment by secretxu** [comment]
@libofei2004 请问你用的效果好的软件是什么，能分享一下吗

**Comment by libofei2004** [comment]
@secretxu 你可以在csdn上搜一下3dtile，里面有人共享，不过这个工具有生成瓦片数的限制

**Comment by fanvanzh** [comment]
@libofei2004 已支持 多级 tileset.json

**Comment by fanvanzh** [comment]
@libofei2004 已调整模型亮度问题。
