### ISSUE TITLE
centos7.3 64位环境下build报错

### ISSUE THREAD

**Issue by luozr** [fanvanzh/3dtiles#254]
报少OSG 、GDAL的相关东西。部分错误如下：
warning: In file included from ./src/gdal/ogr_srs_api.h:35:0,
warning:                  from ./src/gdal/ogr_spatialref.h:35,
warning:                  from ./src/GeoTransform.h:2,
warning:                  from ./src/tileset.cpp:13:
warning: ./src/gdal/ogr_core.h:883:34: 错误：expected initializer before ‘GDALVersionInfo’
warning:  const char CPL_DLL * CPL_STDCALL GDALVersionInfo( const char * );
warning:                                   ^
warning: ./src/gdal/ogr_core.h:899:25: 错误：expected initializer before ‘GDALCheckVersion’
warning:  int CPL_DLL CPL_STDCALL GDALCheckVersion( int nVersionMajor, int nVersionMinor,
warning:                          ^
warning: In file included from ./src/gdal/ogr_spatialref.h:35:0,
warning:                  from ./src/GeoTransform.h:2,
warning:                  from ./src/tileset.cpp:13:
warning: ./src/gdal/ogr_srs_api.h:320:7: 错误：expected initializer before ‘OSRNewSpatialReference’
warning:        OSRNewSpatialReference( const char * /* = NULL */);
warning:        ^
warning: ./src/gdal/ogr_srs_api.h:321:42: 错误：expected initializer before ‘OSRCloneGeogCS’
warning:  OGRSpatialReferenceH CPL_DLL CPL_STDCALL OSRCloneGeogCS( OGRSpatialReferenceH );
warning:                                           ^
warning: ./src/gdal/ogr_srs_api.h:322:42: 错误：expected initializer before ‘OSRClone’
warning:  OGRSpatialReferenceH CPL_DLL CPL_STDCALL OSRClone( OGRSpatialReferenceH );
warning:                                           ^
warning: ./src/gdal/ogr_srs_api.h:323:26: 错误：expected initializer before ‘OSRDestroySpatialReference’
warning:  void CPL_DLL CPL_STDCALL OSRDestroySpatialReference( OGRSpatialReferenceH );

  cargo:warning=./src/gdal/ogrsf_frmts.h:186:32: 错误：‘GDALProgressFunc’未声明
  cargo:warning=                                GDALProgressFunc pfnProgress = NULL,
  cargo:warning=                                ^
  cargo:warning=./src/gdal/ogrsf_frmts.h:156:70: 警告：将 NULL 转换到非指针类型‘int’ [-Wconversion-null]
  cargo:warning=                                       GDALProgressFunc pfnProgress = NULL,

**Comment by luozr** [comment]
补充一下：
 用master的代码，打开了 shp23dtile.cpp 里的 宏 注释；
 环境：centos 7.3  64位的操作系统；
 执行 cargo build --release，报如上那些错。

**Comment by fanvanzh** [comment]
你好，Linux发行版太多，不好做预编译提供。
自己安装gdal、osg 等开发包进行编译，可以参考 #219

**Comment by fanvanzh** [comment]
增加了 Ubuntu/Centos 环境的 编译测试
