### ISSUE TITLE
生成的模型是不是默认加了光照效果？

### ISSUE THREAD

**Issue by libofei2004** [fanvanzh/3dtiles#26]
如图：
![1_3](https://user-images.githubusercontent.com/10001548/41771935-5c9444a8-7649-11e8-940b-b7d8801857d5.PNG)

**Comment by fanvanzh** [comment]
不是，这个是拍摄时现场的光效。
想想你用手机在白天拍照，道理是一样的。

**Comment by libofei2004** [comment]
@fanvanzh 不过我用其他工具转换时是没有这个阴影效果的，有一个工具还有无光效的选项，也许他们的工具在转换时主动去除了模型的光效？

**Comment by fanvanzh** [comment]
@libofei2004 那个工具，能否给个链接？
1、确认你 cesium 里开启光照了吗？
2、如拍摄照片有阴影，只能增强纹理的亮度，去不了阴影。
3、无光照可能是修改了模型的属性，在渲染时不接受阴影。

**Comment by libofei2004** [comment]
@fanvanzh 
工具我分享了一个，链接：https://pan.baidu.com/s/1v5Zpq8IUZ4STLewVYNu8xA 密码：ofav
这个工具转完是没有光照效果的，而且清晰度看上去比你这个工具高。
我没有开光照，照片本身有光照肯定去不了，不过osgb模型也许可以加光照和阴影。

**Comment by fanvanzh** [comment]
谢谢。
我看了下他生成的模型 materials 用的是 shader 实现的， color = texture(u,v) 。
可能我指定的 material 有点问题，偏离了原来的颜色。

**Comment by libofei2004** [comment]
模型精细度的问题估计是什么原因呢

**Comment by fanvanzh** [comment]
geometricError 设置的问题啊， 越小越精细啊

**Comment by libofei2004** [comment]
你是否考虑在程序里改一下生成的geometricError值或者做成可以设置的参数？

**Comment by fanvanzh** [comment]
错误是因为你的文件目录不规范，Tile_+001_+030 目录下需要有个Tile_+001_+030.osgb文件为跟节点模型，而你的数据里变成了 Tile_+001_+030(1).osgb。

ERROR: 2018-07-02 17:48:00 - dir error: D:\BaiduNetdiskDownload\17-18\Data\Tile_+001_+030\Tile_+001_+030.osgb

**Comment by libofei2004** [comment]
嗯，有时候数据来源比较杂，是可能有很多不规范的地方，是否考虑处理一下，遇到不规范文件直接提示后跳过？

**Comment by libofei2004** [comment]
试了你新编出来的工具，有阴影的问题解决了，不过亮度还是不大对，比正常的暗一些，像是黄昏时拍的效果

**Comment by fanvanzh** [comment]
@libofei2004 错误输出就是跳过出错的目录，并且打印出错目录。

**Comment by libofei2004** [comment]
我的意思是错误会导致程序终止，能否让程序避免终止，跳过错误继续处理

**Comment by fanvanzh** [comment]
哦，我没让他跑完。我再确认下是否会有程序终止的问题。

**Comment by fanvanzh** [comment]
![image](https://user-images.githubusercontent.com/10379652/42485217-4c217a44-8429-11e8-9d98-982720ae39f8.png)

经测试，并没有程序异常退出，出错记录都是文件名不规范导致的。

**Comment by fanvanzh** [comment]
fixed now.
