### ISSUE TITLE
centos7编译报错

### ISSUE THREAD

**Issue by haodondon** [fanvanzh/3dtiles#261]
warning: field `version` is never read
   --> src/main.rs:212:9
    |
211 | struct ModelMetadata {
    |        ------------- field in this struct
212 |     pub version: String,
    |         ^^^^^^^
    |
    = note: `ModelMetadata` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `#[warn(dead_code)]` on by default

error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" VSLANG="1033" "cc" "-m64"
  = note: /usr/bin/ld:./lib/libOpenThreads.so: file format not recognized; treating as linker script
          /usr/bin/ld:./lib/libOpenThreads.so:1: syntax error
          collect2: error: ld returned 1 exit status

warning: `_3dtile` (bin "_3dtile") generated 1 warning
error: could not compile `_3dtile` (bin "_3dtile") due to previous error; 1 warning emitted

按照构建流程一步一步走的

**Comment by fanvanzh** [comment]
libOpenThreads.so: file format not recognized;
看上去 so 文件损坏？

**Comment by jay282** [comment]
请问这个怎么解决的？现在碰到同样的问题了。。

**Comment by fanvanzh** [comment]
使用 git 协议clone，而不是 https 协议，试试
