### ISSUE TITLE
请问40680631590769和40408299984661.4数值的来源？

### ISSUE THREAD

**Issue by Hisos** [fanvanzh/3dtiles#267]
这两个数值来自以下函数：
std::vector<double> transfrom_xyz(double radian_x, double radian_y, double height_min){
    // 定义椭球体参数
    double ellipsod_a = 40680631590769;
    double ellipsod_b = 40680631590769;
    double ellipsod_c = 40408299984661.4;

    const double pi = std::acos(-1);
    // 计算坐标转换中的各个分量
    double xn = std::cos(radian_x) * std::cos(radian_y);
    double yn = std::sin(radian_x) * std::cos(radian_y);
    double zn = std::sin(radian_y);

    double x0 = ellipsod_a * xn;
    double y0 = ellipsod_b * yn;
    double z0 = ellipsod_c * zn;
    double gamma = std::sqrt(xn*x0 + yn*y0 + zn*z0);    // 几何意义为物体在地面上的投影点到地心距离的开方
    double px = x0 / gamma;
    double py = y0 / gamma;
    double pz = z0 / gamma;
    ....
}

**Comment by fanvanzh** [comment]
从cesium里抄过来的
