### ISSUE TITLE
convert shapefile failed

### ISSUE THREAD

**Issue by haogewushuang** [fanvanzh/3dtiles#271]
您好，我使用了docker镜像进行测试shp转3dtiles，但是报错了：convert shapefile failed，我的shp文件是ESPG:4326的，但是运行就是不行。
这是我的运行命令：
./target/release/_3dtile --format shape --input /test/height.shp --output /test/3dtiles --height height

**Comment by fanvanzh** [comment]
linux 版本不支持 shp，可以用 windows build

**Comment by haogewushuang** [comment]
几时能支持呀，emm，或者有没有python版的，现在对linux支持度不太好。

**Comment by fanvanzh** [comment]
增加了 Ubuntu/Centos 环境下的编译测试

**Comment by ShareQiu1994** [comment]
> 增加了 Ubuntu/Centos 环境下的编译测试

请问一下，最新的dokcer版本 支持 shp转3dtiles吗  我也遇到了这个问题

**Comment by ShareQiu1994** [comment]
官网上 https://hub.docker.com/r/winner1/3dtiles/tags  最新的容器还是一年前的

> 增加了 Ubuntu/Centos 环境下的编译测试
