### ISSUE TITLE
单个的osgb文件如何转换成3dtile

### ISSUE THREAD

**Issue by kepler-bit** [fanvanzh/3dtiles#278]
你好，我目前有单个的osgb文件，我想把它转换成3dtiles文件，我给它添加了metadata文件，设置了smart3D格式的文件路径，通过软件进行转换，但是结果还是不行

**Comment by kepler-bit** [comment]
请问，这个问题该如何解决

**Comment by kepler-bit** [comment]
GLenum is not GL_TRIANGLES in osgb 这个是其中运行日志的提示

**Comment by fanvanzh** [comment]
单个 osgb 转 glb
3dtile.exe -f gltf -i E:\Data\TT\001.osgb -o E:\Data\TT\001.glb

'GLenum is not GL_TRIANGLES'，这个是数据不规范，没有做三角化处理
