### ISSUE TITLE
代码可以在vs 2015里调试吗？

### ISSUE THREAD

**Issue by libofei2004** [fanvanzh/3dtiles#28]
How to build说明里代码是用cargo build编译的，可以在vs 2015里直接调试编译吗？vs 2010可以吗？

**Comment by fanvanzh** [comment]
可以用 vs 2015 调试。
调试方法： 编译 Debug 版本，运行， 附加到进程

**Comment by libofei2004** [comment]
哦，没有办法直接用vs编源码吗

**Comment by fanvanzh** [comment]
额，确实没有，你可以 fork 一下，把工程改成 vs 的。
