### ISSUE TITLE
关于shp转3dtiles

### ISSUE THREAD

**Issue by lllllleo42** [fanvanzh/3dtiles#280]
![image](https://github.com/fanvanzh/3dtiles/assets/122014332/d2be1014-30d2-4eca-8e87-053457829591)
版主你好，小白想问下为什么会出现这样的问题orz感谢

**Comment by fanvanzh** [comment]
我也不知道，你下载源码 build 吧

**Comment by fanvanzh** [comment]
请下载源码编译，参考主页的 Build
