### ISSUE TITLE
编译成功后，拷贝到其他虚拟机运行吗？

### ISSUE THREAD

**Issue by LYP857** [fanvanzh/3dtiles#285]
我之前用ubutun编译成功后，把整个文件夹压缩拷贝到其他centos7的虚拟机上运行，是会报错 error while loading shared libraries: ./lib/libosg.so.202: file too short的，osgb这些编译后不是离线的吗，为什么还会报错？是环境问题？只能在这编译的环境里面用？

**Comment by fanvanzh** [comment]
应该不行， linux 内核版本不同，程序依赖的C库版本不一样

**Comment by fanvanzh** [comment]
主页增加了 ubutun/centos 的 build 说明
