### ISSUE TITLE
如何调用vs生成的dll，新手求救！

### ISSUE THREAD

**Issue by alibabazzz999** [fanvanzh/3dtiles#297]
编译项目后，在文件夹：“C:\Users\Administrator\Desktop\3Dtiles\3dtiles\vs\x64\Release”下生成了4个文件：“3dtile.dll, 3dtile.lib, 3dtile.exp, 3dtile.pdb ”。
![截图1](https://github.com/fanvanzh/3dtiles/assets/102207130/d3ffee23-76f6-4868-b86a-c4e07ecfbb20)

我写了控制台应用代码去调用dll：
```
#include <iostream>
#include <windows.h>

int main()
{
    std::cout << "Hello World!\n";
    HINSTANCE hDll; // DLL 句柄
    hDll = LoadLibrary(L"3dtile.dll"); // 动态获取 dll 文件的路径
    if (hDll != nullptr)
    {
        std::cout << "DLL loaded successfully!" << std::endl;
        FreeLibrary(hDll);
    }
    else
    {
        // 加载 DLL 失败，打印错误信息
        DWORD dwError = GetLastError();
        std::cerr << "Failed to load DLL: " << dwError << std::endl;
    }
    return 0;
}
```

输出：Failed to load DLL: 126
为何不能调用dll呢。 求解，困扰我两天了。
可是项目中，dll真的存在呀。
![截图2](https://github.com/fanvanzh/3dtiles/assets/102207130/3832b589-2710-46ad-92ef-c8831a4507fa)

**Comment by alibabazzz999** [comment]
![截图1](https://github.com/fanvanzh/3dtiles/assets/102207130/e5ee70e7-5912-455f-97ee-d503f91ae7e8)
![截图2](https://github.com/fanvanzh/3dtiles/assets/102207130/7cb472cb-4b98-4f56-8396-0ad71efdf554)
图片在这里

**Comment by fanvanzh** [comment]
可能没找到 dll 依赖的其他运行库， 最好引用 lib 进行编译，这样比较简单
