### ISSUE TITLE
模型转换成功，但用cesium加载时有问题

### ISSUE THREAD

**Issue by 9lovingly** [fanvanzh/3dtiles#3]
模型很顺利的通过工具转换成功，但是用cesium加载的时候发现，在放大和缩小的过程中，3D Tiles格式的瓦片未全部加载，在某一层级总有缺失。

**Comment by fanvanzh** [comment]
谢谢你，我追踪下看看

**Comment by fanvanzh** [comment]
问题已修复。 @9lovingly
