### ISSUE TITLE
想问下 必须是有data目录才能转换么

### ISSUE THREAD

**Issue by kongfanqiang** [fanvanzh/3dtiles#30]
我现在的问题是：我这边一个区域由好几个osgb文件组成，我通过修改s3c文件将几个osgb放到了一起，但是每个data文件都换成了 data1， data2，data3  有好几个文件夹组成，这样的数据能够转换么  或者每部分转换完了能放到一起发成一个服务么

**Comment by fanvanzh** [comment]
嗯，一个Data文件夹对应一个场景。
现在还不支持多场景的自动合并。
