### ISSUE TITLE
使用PBR参数以后， 材质反而变差了！

### ISSUE THREAD

**Issue by FengFengmomo** [fanvanzh/3dtiles#304]
摘自gltf的版本协议介绍：
Most likely, if you used unlit materials in glTF 1.0, you should use the KHR_materials_unlit extension in glTF 2.0. If you used blinn, phong, or lambert, you should use metal/rough or spec/gloss PBR in glTF 2.0. The PBR conversion of those materials should look quite good, although if you're looking for an exact match of the legacy materials, you may need to consider the custom GLSL extension.
但是我使用pbr参数以后，材质反而变差了。

**Comment by FengFengmomo** [comment]
对比了正常文件，应该是b3dm文件里的json少了两个字段：	"extensionsRequired": [
		"KHR_materials_unlit"
	],
	"extensionsUsed": [
		"KHR_materials_unlit"
	],

**Comment by FengFengmomo** [comment]
我使用了它的工具转换出来材质显示是正常的，同时用你的工具得到的json替换掉这个作者的工具转换得到的json，材质依然不清晰，这个是另外一个作者的链接：https://github.com/scially/Cesium3DTilesConverter

**Comment by fanvanzh** [comment]
你使用的是最新代码吗？ 代码里可以搜到     
```
model.extensionsRequired = { "KHR_materials_unlit" };
model.extensionsUsed = { "KHR_materials_unlit" };
```

**Comment by FengFengmomo** [comment]
> 你使用的是最新代码吗？ 代码里可以搜到     
> ```
> model.extensionsRequired = { "KHR_materials_unlit" };
> model.extensionsUsed = { "KHR_materials_unlit" };
> ```

我用的是你build好的程序进行转换的。

**Comment by FengFengmomo** [comment]
> 我使用了它的工具转换出来材质显示是正常的，同时用你的工具得到的json替换掉这个作者的工具转换得到的json，材质依然不清晰，这个是另外一个作者的链接：https://github.com/scially/Cesium3DTilesConverter

这个是让我最奇怪的，b3dm文件都是一样的，换个tileset.json就还是材质不清晰的了。可能问着这个问题比较愚蠢，没有学过transform相关知识。

**Comment by fanvanzh** [comment]
自己拉源码 build 一个，估计是很久之前的代码了

**Comment by fanvanzh** [comment]
参考主页 Build 最新代码
