### ISSUE TITLE
执行的时候直接弹出错误框  能看下么 

### ISSUE THREAD

**Issue by kongfanqiang** [fanvanzh/3dtiles#31]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	3dtile.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5b36edea
  故障模块名称:	osg130-osg.dll
  故障模块版本:	3.4.0.130
  故障模块时间戳:	5a2b8569
  异常代码:	c0000005
  异常偏移:	0000000000099b49
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	7bc5
  其他信息 2:	7bc563e6e8d4a0ed169efefcbb9eb870
  其他信息 3:	d976
  其他信息 4:	d97655671236aa81456aa559c949ce78

**Comment by fanvanzh** [comment]
这个看不出来问题。
好像是 osg 模型解析模块出问题了
