### ISSUE TITLE
想问下，你这个工具当单个osgb文件超过1M的时候是不是会报错？我发现我报错的地方都是osgb文件超过1M的地方？

### ISSUE THREAD

**Issue by kongfanqiang** [fanvanzh/3dtiles#32]

**Comment by fanvanzh** [comment]
可以发个 osgb > 1M 的文件给我试试，应该和大小无关。
可能是数据内容的问题。

**Comment by kongfanqiang** [comment]
[Tile_+009_+029.zip](https://github.com/fanvanzh/3dtiles/files/2238377/Tile_%2B009_%2B029.zip)
本来就想把文件给你让你看看，结果我一直上传不了，

**Comment by kongfanqiang** [comment]
帮忙看下

**Comment by fanvanzh** [comment]
模型存在空的PrimitiveSets问题，导致程序出错。
已更新修复

**Comment by kongfanqiang** [comment]
多谢啊  你预编译的那个下载地址里面的内容 更新了我下载用下么，我这边没有编译环境

**Comment by fanvanzh** [comment]
是的。代码提交后，预编译的就会自动生成。

**Comment by kongfanqiang** [comment]
好的 知道了
