### ISSUE TITLE
贴图纹理

### ISSUE THREAD

**Issue by GISerWYJ** [fanvanzh/3dtiles#33]
请问支持超图导出的osgb数据吗，尝试了以下转换后没有贴图呢。
![image](https://user-images.githubusercontent.com/12789732/43390687-5f5d75c4-9421-11e8-9159-ffb8ce6fcdc5.png)

**Comment by fanvanzh** [comment]
没试过超图转出的 osgb ，可以上传个 文件给我试试

**Comment by fanvanzh** [comment]
更新了对 DXT 压缩纹理的支持，您再试下。
也可以调试下，告知我这个模型用的什么纹理。
