### ISSUE TITLE
想问下 osgb转3dtiles 的时候坐标系能转么  投影换成地理

### ISSUE THREAD

**Issue by kongfanqiang** [fanvanzh/3dtiles#34]

**Comment by kongfanqiang** [comment]
想问下 你的配置中 x:120  y:30 是什么意思

**Comment by fanvanzh** [comment]
指定模型的中心点。
将模型的中心点，放到经纬度 （120，30 ）的地方。

**Comment by kongfanqiang** [comment]
我的osgb数据是cgcs2000 高斯投影的  你这个工具能转成wgs84的吗

**Comment by fanvanzh** [comment]
可以的。 默认是解析 metadata.xml 里描述的坐标信息。

**Comment by fanvanzh** [comment]
不一定有哦。
CC 处理的模型，会有个 metadata.xml 来说明模型中心点所在的经纬度。
如果没有 metadata.xml 也没指定经纬度，模型会加载到经纬度 （0,0）处。

**Comment by kongfanqiang** [comment]
哦哦  知道了   有metadata文件就不必指定中心点了 ，，没有的话要自行指定是吧

**Comment by fanvanzh** [comment]
是的。
