### ISSUE TITLE
怎么用vs调试？

### ISSUE THREAD

**Issue by yeyan00** [fanvanzh/3dtiles#36]
你好：
十分感谢您能提供代码，我看您代码既有c++又有rust，rust这一块没用过，我看你提供的编译方式是通过命令行，是否可以用vs编译整个项目进行调试？
因为之前用工具处理大量的模型时遇到无法转换的问题，想跟代码调试一下，能方便告诉一下这个流程怎么做吗？
谢谢！

**Comment by fanvanzh** [comment]
可以用 vs 附加到进程调试。
现在是否还有处理大量模型时无法转换的问题呢？

我开这个项目，也有试用 rust 的目的，没想到后面 cpp 越来越多，就混编了。
其实你自己改成纯 c++ 的也不难。

**Comment by yeyan00** [comment]
好的，我试试，谢谢！

**Comment by fanvanzh** [comment]
readme 增加了 vs 编译调试指南
