### ISSUE TITLE
osgb转3dtile，多个切片只能转一个，高度调节为负数，cesium加载显示离地面更高了

### ISSUE THREAD

**Issue by Tonynovtop** [fanvanzh/3dtiles#37]
1. 多个切片只能转一个
数据链接：https://pan.baidu.com/s/1t4Kwje-Hd7G-RRTSAWPnoQ 密码：7lb9
转换前数据
![image](https://user-images.githubusercontent.com/41135574/43998625-8cdaa494-9e2c-11e8-96d0-4628aaaafbb0.png)
![image](https://user-images.githubusercontent.com/41135574/43998628-9b5a195a-9e2c-11e8-8f18-377761435000.png)
转换设置
![image](https://user-images.githubusercontent.com/41135574/43998646-fb778b9c-9e2c-11e8-84be-61de92b07f2c.png)
转换后数据
![image](https://user-images.githubusercontent.com/41135574/43998635-c2c897dc-9e2c-11e8-8d3e-d5c5de395811.png)
![image](https://user-images.githubusercontent.com/41135574/43998640-d6b6bc7e-9e2c-11e8-953b-8ae415c34fc6.png)
2.高度设置为负数
转换设置
![image](https://user-images.githubusercontent.com/41135574/43998659-4b57269a-9e2d-11e8-9388-0643dd55c459.png)
cesium加载未设置前
![image](https://user-images.githubusercontent.com/41135574/43998668-916fcefc-9e2d-11e8-9fb0-e438431a40d5.png)
设置后
![image](https://user-images.githubusercontent.com/41135574/43998694-45592fee-9e2e-11e8-9a95-2219354d3707.png)
请问下，这是什么原因呢？

**Comment by fanvanzh** [comment]
错误提示都是有原因的，因为缺少 Tile_002_020.osgb 文件，无法确定根节点在哪儿。

offset 为负数的情况，我要测试下，不确定是否有bug。

**Comment by Tonynovtop** [comment]
不设置offset值，贴地面还比较近，设置值之后都会使模型离地面更高
![image](https://user-images.githubusercontent.com/41135574/43999912-cd3ba21a-9e48-11e8-9326-48d60c0f3d36.png)

**Comment by Tonynovtop** [comment]
如果这样的话，只有在cesium加载模型时设置参数了

**Comment by fanvanzh** [comment]
经测试，设置为负值是有用的，但是 cesium 并不会盖住地表下面的模型。
你这个模型可能本来基准点就是负数，你设置的负数太小了，反而上升了。
