### ISSUE TITLE
osgb转到3dtiles后生成的tileset.json数据没有边界球

### ISSUE THREAD

**Issue by gitzhang** [fanvanzh/3dtiles#39]
生成后的数据没有BoundingSphere，在Cesium中浏览时影响相机

**Comment by fanvanzh** [comment]
生成的 tileset 是用的 BoundingBox。
我认为不需要用 BoundingSphere。

**Comment by dingslin** [comment]
通过pix4d的.osgb数据可以通过这个软件得到3dtiles吗

**Comment by fanvanzh** [comment]
通过pix4d的.osgb数据长什么样？
能否截个图看看数据组织方式。
