### ISSUE TITLE
About FBX converting to b3dm

### ISSUE THREAD

**Issue by 9lovingly** [fanvanzh/3dtiles#4]
I try it,but the tool couldn't support it now?

**Comment by fanvanzh** [comment]
yes, it`s in the plan.

**Comment by 9lovingly** [comment]
When will the tool support converting the FBX to the b3dm?

**Comment by fanvanzh** [comment]
about several of weeks.

**Comment by 9lovingly** [comment]
Hi,How about the progress of converting the FBX to the b3dm?

**Comment by fanvanzh** [comment]
not begin yet

**Comment by 9lovingly** [comment]
May I join you ? I research the tools several months.

**Comment by fanvanzh** [comment]
welcome!!

**Comment by fanvanzh** [comment]
https://github.com/fanvanzh/3dtiles/invitations
