### ISSUE TITLE
转化过程中，提示metadata文件出错，但是还是能够继续转化，后来测试在图层上的叠加位置不对，请问如何解决？谢谢

### ISSUE THREAD

**Issue by fnd9966** [fanvanzh/3dtiles#40]
ERROR: 2018-08-30 13:53:37 - parse E:\test\main\metadata.xml failed

**Comment by fnd9966** [comment]
![0m4p s4 x o c76c 77 1](https://user-images.githubusercontent.com/35514653/44832395-57d03900-ac5d-11e8-84a6-e7c0453b406c.png)
metadata里面的内容大致是这样的，是否是该文件本身的问题？

**Comment by fanvanzh** [comment]
你的 metadata.xml 和我假设的结构不一样，导致无法解析。
根目录有个 matrix.xls 表格文件，你可以自己把经纬度转成矩阵，替换 tileset.json 里的 transform

**Comment by fnd9966** [comment]
谢谢回答，再次请教一下，matrix.xls中的x,y是指什么，是否必填
![hy2n0 h7_wh v6e j a9](https://user-images.githubusercontent.com/35514653/44837953-90780e80-ac6d-11e8-8623-22b8a26032d0.png)
生成的的matrix怎么对应metadata里面的transform
![am6bf7bw30t r va 4bmp 1](https://user-images.githubusercontent.com/35514653/44838084-e2209900-ac6d-11e8-9354-c03a5bb93fe8.png)
![o3z2p3bn 19_skj21tt f30](https://user-images.githubusercontent.com/35514653/44838094-e64cb680-ac6d-11e8-921a-e4ef91677110.png)
谢谢

**Comment by fanvanzh** [comment]
x,y 不用填。竖着一列一列来。

**Comment by fanvanzh** [comment]
看来还是不好使，得做个带界面的。
