### ISSUE TITLE
转换成功后数据对不上底图，角度和比例怎么调整

### ISSUE THREAD

**Issue by simonasdmd** [fanvanzh/3dtiles#45]
数据成功转换之后，发现模型和底图对不上（大小和角度），想问下这个可以怎么调整。如图：
![image](https://user-images.githubusercontent.com/42527845/47067660-b3aa4d80-d21c-11e8-9e3d-0c28ccb92743.png)

求助~

**Comment by simonasdmd** [comment]
看样子 如果放大一下 然后角度调整一下就对上了

**Comment by simonasdmd** [comment]
@fanvanzh 这个转换出来的可以放大和调整角度吗？我试了下里面自带的martix 高度和经纬度可以调整，但是角度和大小不知道怎么调整，请教一下~多谢

**Comment by fanvanzh** [comment]
你可以自己旋转、缩放矩阵试试。
看看 Cesium 里的 Matrix 旋转操作。

原来有计划做个可视化工具的，一直没实施。
