### ISSUE TITLE
请问transform与box间有什么关系，如何计算tileset.json坐标？

### ISSUE THREAD

**Issue by sophia-xll** [fanvanzh/3dtiles#47]
你好，请问transform与box间有什么关系，如何计算tileset.json坐标？

我在https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tile-transform中找到transform叶子节点与根结点计算公式：
![transform](https://user-images.githubusercontent.com/25217255/47980099-abab3400-e08b-11e8-8e24-a5bee40c4e9e.png)

tileset.json内容：
{"asset": {"version": "1.0"},
"geometricError": 1319.96566351801,
"root": {
"boundingVolume": {
"box": [
1.04773789644241e-9, -0.504322739783674, -0.616247923113406,
5641.31597575976, 0, 0, 0,
6311.33777747117, 0, 0, 0, 25.8459681412205]
},
"children": [
{
"boundingVolume": {
"box": [
2797.89169446776, -3133.07355675142, 12.5403080463512,
2843.42428129305, 0, 0,
0, 3180.84259900837, 0,
0, 0, 15.1854221645246 ]},
"content": {"url": "tileset_1_1_0.json"},
"geometricError": 164.995707939751,
"refine": "REPLACE"
}]
"geometricError": 329.991415879503,
"refine": "REPLACE",
"transform": [
-0.895897517499185, -0.444260777177997, 0, 0,
0.283927872032897, -0.572569735547873, 0.769122136866122, 0,
-0.341690798268945, 0.689054613072027, 0.639101821764334, 0,
-2176357.29229105, 4388848.16197401, 4070680.03399528, 1
]
}
}

tileset_1_1_0.json为：
{"asset": {"version": "1.0"},
"root": {
"boundingVolume": {
"box": [
2.3283064365387e-10, -0.113443724578246, 3.57330994307995,
2843.42474428168, 0, 0,
0, 3179.80389127671, 0,
0, 0, 15.5025072079152]
},
"children": [],
"content": {"url": "1/1/0.b3dm"},
"geometricError": 164.995707939751,
"refine": "REPLACE",
"transform": [
0.999999837172188, 0.00036471139259886, -0.000438909100338114, 0,
-0.000364495423816037, 0.999999812521052, 0.000492037546955482, 0,
0.000439088469750899, -0.000491877486479553, 0.999999782628903, 0,
2796.72426339705, -3132.95792494155, 8.96653714217246, 1]
}
}
请问，tileset_1_1_0.json中的box，是如何计算为tileset.json中children里的box的？

**Comment by fanvanzh** [comment]
transform 是矩阵的描述： 平移、缩放、旋转。
box 是节点的外包矩形。

tileset.json： 我目前的计算方式就是 取子节点的 bbox， 赋值给 tileset

**Comment by sophia-xll** [comment]
@fanvanzh 谢谢，您知道transform的4*4矩阵中， 具体哪几个元素控制平移、哪几个控制缩放、哪几个控制旋转吗？

**Comment by fanvanzh** [comment]
这个您买本书看看吧。
