### ISSUE TITLE
将osgb转的3dtile加载到cesium上，镜头缩放和旋转都会出现部分tile显示缺失

### ISSUE THREAD

**Issue by Tonynovtop** [fanvanzh/3dtiles#48]
![image](https://user-images.githubusercontent.com/41135574/47982250-06837080-e10a-11e8-9a22-754236995f31.png)

**Comment by Tonynovtop** [comment]
以上是加载3dtile的效果图，用cesiumlab将osgb转成3dtile，同样进行加载，发现不会出现这种情况，如图
![image](https://user-images.githubusercontent.com/41135574/47982526-046de180-e10b-11e8-889b-15e729825921.png)

两者转出后的数据组织结构如下：
1、3dtile.exe(与官方展示的数据结构一致)
![image](https://user-images.githubusercontent.com/41135574/47982675-91189f80-e10b-11e8-93ae-dda42a0759c2.png)
![image](https://user-images.githubusercontent.com/41135574/47982782-f2407300-e10b-11e8-9510-2d1b2b7870e7.png)
2、cesiumlab
![image](https://user-images.githubusercontent.com/41135574/47982845-2ddb3d00-e10c-11e8-9ff8-20c00bcbe72d.png)
![image](https://user-images.githubusercontent.com/41135574/47982877-4ba8a200-e10c-11e8-8fa7-2c7c62e964d7.png)
![image](https://user-images.githubusercontent.com/41135574/47982858-3c295900-e10c-11e8-9054-6f4a9b6ad34b.png)

请问下，是否因为组织方式的原因导致镜头推进旋转切片显示缺失呢？

**Comment by fanvanzh** [comment]
测试数据能否分享下。

**Comment by Tonynovtop** [comment]
好，我加你qq

**Comment by fanvanzh** [comment]
不好意思，我的qq是： 954157387。加这个。

**Comment by fanvanzh** [comment]
use command like this to convert you data
```
3dtile -f osgb -i E:\Data\osgb\osgb -o E:\test_3d\cesium1.42\testApp\testData -c "{\"offset\": 20}"
```

make sure all the data is on the groud.

**Comment by xiaozhiquan** [comment]
using 3dtile param maxlvl, error cames out  bbox is empty how to solve it
