### ISSUE TITLE
vs2015编译问题

### ISSUE THREAD

**Issue by bianbian886** [fanvanzh/3dtiles#51]
大神，我用git clone download 的代码，用您说的vs 调试指南，出现：
![om rl7o_k7 mo2wxu i_ u](https://user-images.githubusercontent.com/45083910/48605918-0d876a00-e9b9-11e8-8f41-9fb310ff3019.png)
如果我用网页版的下载，用vs调试指南的步骤，出现：
![qq 20181116121432](https://user-images.githubusercontent.com/45083910/48605951-298b0b80-e9b9-11e8-84a4-9d83e2c83f7a.png)

**Comment by bianbian886** [comment]
图一的最终报错是：
![4 n g0 im 7 gse _ n utu](https://user-images.githubusercontent.com/45083910/48606473-a1a60100-e9ba-11e8-86f3-6dd1a30c7837.png)

**Comment by fanvanzh** [comment]
切换到 release
先编译 tile 工程，这个是 dll
再编译TileMaker

**Comment by bianbian886** [comment]
您好，还得请教一下，按照您说的，还是有以下报错，并不确定是最终影响编译的问题。
![1542596139 1](https://user-images.githubusercontent.com/45083910/48683843-fda29c80-ebe9-11e8-8530-8e320662e54c.jpg)
![y a3hcc8tjc kpqkh 5jxf](https://user-images.githubusercontent.com/45083910/48683846-02675080-ebea-11e8-80cc-1feaf7097875.png)

**Comment by bianbian886** [comment]
已解决，一定要把tile.dll，生成到bin 文件夹下面
![kw u3 j3hlri6x 7y9pr 5n](https://user-images.githubusercontent.com/45083910/48752252-3febdc80-ecc3-11e8-82e2-1f1e3da1f31b.png)

**Comment by 623823676lool** [comment]
你环境变量怎么配置的，为什么我将其放在bin下还是报那一堆错误
