### ISSUE TITLE
求问下boundingVolume和geometricError是由原osgb决定的还是在本工具转换过程中设定的？

### ISSUE THREAD

**Issue by simonasdmd** [fanvanzh/3dtiles#53]
求问 boundingVolume和geometricError是由原osgb决定的还是在本工具转换过程中设定的？
box region sphere

![image](https://user-images.githubusercontent.com/42527845/48765727-c2899180-eced-11e8-8b1e-c316161da809.png)

**Comment by fanvanzh** [comment]
在本工具转换过程中设定

**Comment by simonasdmd** [comment]
@fanvanzh 有两个问题 
1.如果是在工具转换过程中设定 那么如果想把一个大块拆成更多的小块或者一个大块不想拆成更多的小块可以怎么设定呢？（另外问下geometricError是不是决定拆成块的大小和数量）
2.boundingVolume里面box region sphere是由什么决定的？
