### ISSUE TITLE
shp转3dtile显示不正常

### ISSUE THREAD

**Issue by dajiang31835008** [fanvanzh/3dtiles#54]
你好，我编译了最新版的工具，转换建筑物轮廓shp数据，指定了高度字段，3dtile -f shape --height height -i  。。。，转换过程正常，加载到cesium中显示不正常，建筑没有拉起体块，底面结构也不对，具体效果如下，请问这是啥原因？
![image](https://user-images.githubusercontent.com/10216564/48777451-8ebe6400-ed0d-11e8-99bf-e87c45812357.png)

**Comment by bianbian886** [comment]
我也是这样子的，3dtile.exe -f shape --height height -i E:\tdt_data\Export_Output.shp -o E:\tdt_data\test，没用哈

**Comment by fanvanzh** [comment]
@dajiang31835008 @bianbian886 
方便加我QQ，提供下测试数据吗？
954157387

**Comment by fanvanzh** [comment]
@bianbian886 结论是 带洞面数据 支持不好？

**Comment by bianbian886** [comment]
是的，一定要是简单的面状数据；同时请问，现有软件中的shp23dtiles是可以用vs2015编译的吗？ @fanvanzh

**Comment by dajiang31835008** [comment]
@bianbian886 你好，我用qgis提供的Delete holes工具和Check validity工具，对矢量数据空geomety和含洞面数据进行了处理，最终生成的3dtile还是显示不正常。我是用vs2015编译的
![image](https://user-images.githubusercontent.com/10216564/49452918-0ff11d00-f81d-11e8-97cd-c99f688c49ca.png)
![image](https://user-images.githubusercontent.com/10216564/49452936-1bdcdf00-f81d-11e8-957d-3fc5cb283c9b.png)
![image](https://user-images.githubusercontent.com/10216564/49452970-27c8a100-f81d-11e8-9a81-aebdb239fb9c.png)

**Comment by bianbian886** [comment]
vs2015的，我还没编译出来，我用的楼主原生cmd做的测试发现空洞情况和叠加的，导致显示不出来，你如果编译出来了，可以用arcmap 删除空洞数据，或者找一些测试，简单的shp直接试一下效果好了

**Comment by bianbian886** [comment]
插个队，楼主，请问我用vs2015编译生成的osgb,转换视角（放大或者旋转到一定角度），会出现模型的消失或者残缺
![qq 20181206141745](https://user-images.githubusercontent.com/45083910/49565380-f4435f00-f961-11e8-80bd-d04adac7fafd.png)
![qq 20181206141750](https://user-images.githubusercontent.com/45083910/49565391-f9a0a980-f961-11e8-86b3-2af363ed9427.png)
请问，这个应该跟哪个有关，怎么改

**Comment by fanvanzh** [comment]
@bianbian886 用项目首页的，预编译下载 试试呢？

**Comment by dajiang31835008** [comment]
@fanvanzh @bianbian886 请问，我换了一个面状数据源，生成的瓦片有高度了，但还是显示不正常：
![image](https://user-images.githubusercontent.com/10216564/49695580-45f51f00-fbd8-11e8-9c12-65cd19cbac78.png)
我创建了几个简单的矢量面，用其他工具和本工具切出来的瓦片效果如下：
![image](https://user-images.githubusercontent.com/10216564/49695602-83f24300-fbd8-11e8-9e27-eca65deee5de.png)
![image](https://user-images.githubusercontent.com/10216564/49695604-89e82400-fbd8-11e8-8644-0b08d45fc33a.png)
本工具切出来的还是不太正常

**Comment by fanvanzh** [comment]
@dajiang31835008 

thank you。
我抽时间研究下。

**Comment by fanvanzh** [comment]
确认下 --height xx， 字段名字对吗？
我新加了一个 b3dm 转 glb 的功能， 你可以把 b3dm 准成 glb 在线看看数据对不对。

**Comment by fanvanzh** [comment]
@dajiang31835008 也可能是 shapefile 转出的 geometricError 大小不合适。你调整下试试。

**Comment by dajiang31835008** [comment]
@fanvanzh 感谢回复！高度字段没有问题。设置geometricError是手动修改生成的tileset.json文件里的geometricError 值吗 ，我改成2000了还是有问题，效果如下：
 
![image](https://user-images.githubusercontent.com/10216564/50012922-d24d7a80-fffa-11e8-96d4-a4705f7dd57b.png)

   我打wireframe模式后，显示效果如下：
![image](https://user-images.githubusercontent.com/10216564/50012878-c19d0480-fffa-11e8-89b0-1c356bf7fc70.png)

**Comment by fanvanzh** [comment]
看上去模型跑到了网格下方。
shape转三维形状应该是对的。

可能是：
1、你的面底面太大，渲染时被部分裁剪了。
2、数据跑到了网格下方。

尝试用个小数据试试，调整下 3dtile 的高度试试。

**Comment by lqzer** [comment]
您好!我用预编译下载的实现shp转3dtile，转换之后加载失败。
报这样的错。
A 3D tile failed to load: http://localhost:8080/webGIS/data/build/tile/0/0/0.b3dm?v=0.0  
Error: Unexpected token  in JSON at position 19

**Comment by fanvanzh** [comment]
> 您好!我用预编译下载的实现shp转3dtile，转换之后加载失败。
> 报这样的错。
> A 3D tile failed to load: http://localhost:8080/webGIS/build/tile/0/0/0.b3dm?v=0.0
> Error: Unexpected token in JSON at position 19

fixed

**Comment by fanvanzh** [comment]
these issues should be fixed now.

**Comment by dajiang31835008** [comment]
@fanvanzh 谢谢你的回复和修改！问题已解决

**Comment by DonnaLh** [comment]
> @fanvanzh 谢谢你的回复和修改！问题已解决

您好，请问怎么解决的，我也遇到同样的问题，数据量大的时候，部分面不能正常显示

![image](https://user-images.githubusercontent.com/38528100/163085586-6024cb2d-d015-493b-a822-5a4ed5dfd874.png)
