### ISSUE TITLE
OSGB转3dtile不能显示

### ISSUE THREAD

**Issue by zhongshuiyuan** [fanvanzh/3dtiles#55]
你好，现在手上有一批osgb文件，使用这个工具转换，转换没有出错正常结束，但在cesium上无法显示，一丁点都没有显示，能帮我看看是什么原因吗？

**Comment by simonasdmd** [comment]
你可以把osgb的目录结构截图发下，之前我也碰到过这个问题，同时你再加载的时候按下f12看下发了那些请求，有没有对应的json请求和b3dm加载，可能并不是没有，只是闪了一下就没有了。

**Comment by zhongshuiyuan** [comment]
![1](https://user-images.githubusercontent.com/8955999/48835022-2bd6d680-edba-11e8-92dd-899baa27f9a6.jpg)
![2](https://user-images.githubusercontent.com/8955999/48835033-3002f400-edba-11e8-8fb8-f85e619ccbfb.jpg)
![3](https://user-images.githubusercontent.com/8955999/48835037-32654e00-edba-11e8-83c8-cf0833ba6b84.jpg)

这个是文件结构，F12下看，都全部加载了，但视图里就是看不到

**Comment by simonasdmd** [comment]
你把页面下面的海拔 经纬度 还有视角高度 都截下图，还有f12加载的也截图发下看看

**Comment by zhongshuiyuan** [comment]
![1](https://user-images.githubusercontent.com/8955999/48880984-e4018f00-ee4d-11e8-82a3-38b729c7f1da.jpg)
@simonasdmd

**Comment by zhongshuiyuan** [comment]
![1](https://user-images.githubusercontent.com/8955999/48887810-9c89fb80-ee6b-11e8-862a-38143f2009de.jpg)
清理过很多次缓存，也没发现有什么闪一下，也还是一样，这个metadata.xml，加qq，我把数据给你看一下，419042777
@simonasdmd

**Comment by simonasdmd** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	
	<SRS>ENU:22.64785,113.06277</SRS>
	
	<SRSOrigin>0,0,0</SRSOrigin>
</ModelMetadata>




你把这个代替这个metadata.xml 你的全部删掉 换成这个然后再重新转换一份，再把转换出来总得那个tilejson最后 transfrom截图发下

**Comment by simonasdmd** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	
	<SRS>ENU:22.64785,113.06277</SRS>
	
	<SRSOrigin>0,0,0</SRSOrigin>
</ModelMetadata>

**Comment by simonasdmd** [comment]
这里 刚才复制不知道为啥发不出去
![image](https://user-images.githubusercontent.com/42527845/48892415-f6dd8900-ee78-11e8-9f74-05d5797f3495.png)

**Comment by zhongshuiyuan** [comment]
好了
![1](https://user-images.githubusercontent.com/8955999/48896375-71f76d00-ee82-11e8-97c2-9a26aed5845a.jpg)

[tileset.zip](https://github.com/fanvanzh/3dtiles/files/2607533/tileset.zip)

**Comment by simonasdmd** [comment]
加载出来了吗？

**Comment by zhongshuiyuan** [comment]
没有，结果还是一样，没看见什么闪的，也没数据

**Comment by zhongshuiyuan** [comment]
可能找到原因了，可能是场景发生缩放的原因，能加入判断且自动调整为最佳场景大小再切片吗
@simonasdmd

**Comment by simonasdmd** [comment]
这个工具只是转换，最多就是调解下高度之类的，至于内部的层级还有属性都是osgb数据本身的，没办法改变

**Comment by zhongshuiyuan** [comment]
后来我转成站心坐标系的OSGB就能用了，目测只支持站心坐标系。

**Comment by simonasdmd** [comment]
嗯，能用了就好~

**Comment by simonasdmd** [comment]
顺便问下你知不知道boundingVolume和geometricError是由原osgb决定的还是在工具转换过程中设定的？

**Comment by zhongshuiyuan** [comment]
都是osgb决定的，wgs84坐标系的OSGB转换后看不见，就是因为程序计算boundingVolume和geometricError采用的是站心坐标系的计算方法，不知道程序以后会不会加入wgs84坐标系下boundingVolume和geometricError的计算方法.
@simonasdmd 
@fanvanzh

**Comment by fanvanzh** [comment]
现在都是按 站心坐标系 计算的， 转 wgs84 是通过 root 目录下的 transform 实现的。
simonasdmd 很热心，非常感谢你。

**Comment by fanvanzh** [comment]
@simonasdmd 我的代码就是把 osgb 的 node 转成 cesium 的 tile。
不拆分，需要写代码去实现 osgb node 的合并，在 node visitor 里面实现多个物理node合并成一个逻辑node。

geometricError 是控制模型什么时候出现，什么时候消失。 （类似于 Lod 的精度控制）

boundingVolume里面box region sphere 是由 tile 的范围决定的。都表示范围，形式不同而已。
