### ISSUE TITLE
cesium 1.50以上版本会报KHR_technique_webgl错误

### ISSUE THREAD

**Issue by junyuz** [fanvanzh/3dtiles#56]
需要升级扩展到KHR_technique**s**_webgl，多了一个s，对属性做一些修改，添加programs，shaders，techniques

**Comment by fanvanzh** [comment]
thank you. 
please refer #43 to resolve your problem.

update will in the plan

**Comment by junyuz** [comment]
> thank you.
> please refer #43 to resolve your problem.
> 
> update will in the plan

thanks

**Comment by fanvanzh** [comment]
the update has already done!
