### ISSUE TITLE
转出的3dtiles新版本cesium已经不能识别。

### ISSUE THREAD

**Issue by Rackar** [fanvanzh/3dtiles#58]
发现了如下文章有过对这个问题的描述

https://www.jianshu.com/p/e0e0a62c5726
供作者参考，不知道大神还能否更新适配……

**Comment by fanvanzh** [comment]
thank you.
please refer #43 to resolve your problem.

**Comment by Rackar** [comment]
感谢回复，已用引用代码修复，加载出少量倾斜模型数据，但是在加载到GB级数据时Cesium崩溃，正在查找原因。。

**Comment by fanvanzh** [comment]
应该是你显存不足
