### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yanliasdf789** [fanvanzh/3dtiles#6]
![github1](https://user-images.githubusercontent.com/21374630/37940737-e6ded890-319c-11e8-8458-3b35d7b2ea5b.png)

**Comment by fanvanzh** [comment]
看上去是你的 cl 编译器没装好。
你安装 vs 2015时候，是否勾选 c++ 了？

**Comment by fanvanzh** [comment]
请发下你的操作信息。
这个工程目前只能在 x64 平台编译工作

**Comment by tang-huaming** [comment]
HI fanvanzh, 我也遇到了相同的问题，可以确定是x64平台，并且我可以直接运行cl.exe命令，是不是传递的编译参数存在问题

![image](https://user-images.githubusercontent.com/14356009/38035177-647f4b06-32d6-11e8-902e-69755fc5bf75.png)

**Comment by fanvanzh** [comment]
你们都是 社区版本的 Vs2015 吗？

**Comment by kickasss** [comment]
同问，编译失败，vs2015专业版，win10 x64

**Comment by fanvanzh** [comment]
我在 ReadMe 中提供了每日构建编译结果下载。

**Comment by fanvanzh** [comment]
根据最新的测试发现，使用网页下载的方式可能会导致编译不过去。
请使用 git clone https://github.com/fanvanzh/3dtiles拉取代码

**Comment by fanvanzh** [comment]
根据最新的测试发现，使用网页下载的方式可能会导致编译不过去。
请使用 `git clone https://github.com/fanvanzh/3dtiles`拉取代码
