### ISSUE TITLE
shape转换问题

### ISSUE THREAD

**Issue by junyuz** [fanvanzh/3dtiles#61]
shape文件转换会导致cpu飙升，导致操作系统无响应

**Comment by fanvanzh** [comment]
可否共享一下数据文件，和转换命令。

**Comment by junyuz** [comment]
> 可否共享一下数据文件，和转换命令。

可以啊，留一下邮箱吧，我发给你

**Comment by ahahahahalo** [comment]
您好，请问一下，您是用代码转换的，还是编译好的exe转换的呢 @junyuz

**Comment by junyuz** [comment]
> 您好，请问一下，您是用代码转换的，还是编译好的exe转换的呢 @junyuz

用预编译好的exe转换的

**Comment by ahahahahalo** [comment]
> > 您好，请问一下，您是用代码转换的，还是编译好的exe转换的呢 @junyuz
> 
> 用预编译好的exe转换的

好吧，我这exe也可以，但是老大不给引用exe，只给引用dll，，，，，，不会调用😭

**Comment by junyuz** [comment]
> > > 您好，请问一下，您是用代码转换的，还是编译好的exe转换的呢 @junyuz
> > 
> > 
> > 用预编译好的exe转换的
> 
> 好吧，我这exe也可以，但是老大不给引用exe，只给引用dll，，，，，，不会调用😭

这个转换bug是和数据有关的，不是所有数据都有问题，如果想要引用dll，那只能自己重新封装一下了

**Comment by ahahahahalo** [comment]
换了个shape试了下，也出现cpu和内存飙升的问题了😀

**Comment by fanvanzh** [comment]
加我QQ 发吧。 954157387

**Comment by fanvanzh** [comment]
由于 Cesium 只支持 WGS-84 坐标系数据， 请确认数据是否是 WGS84 的。
