### ISSUE TITLE
怎么调用windows下编译好的dll

### ISSUE THREAD

**Issue by ahahahahalo** [fanvanzh/3dtiles#62]
![image](https://user-images.githubusercontent.com/46733082/51221155-4751fe00-1973-11e9-81b0-60f195a01a07.png)
现在用编译好的3dtiles.exe是可以实现shape转3dtile的，但是想直接调dll，而不是exe的方式，写在代码里，该如何实现呢 @fanvanzh ，谢谢

**Comment by fanvanzh** [comment]
这个得改代码。
有偿定制，或者你自己研究研究。

**Comment by ahahahahalo** [comment]
![image](https://user-images.githubusercontent.com/46733082/51293235-eb59a900-1a48-11e9-85cf-5b33312007c7.png)
请问下这个参数该传啥

**Comment by ahahahahalo** [comment]
![image](https://user-images.githubusercontent.com/46733082/51293808-5e641f00-1a4b-11e9-8412-b045d708720f.png)
新建文件夹报了个错😭

**Comment by ahahahahalo** [comment]
hi，我用代码把shp转成tile了，可是还缺一个tileset.json文件，该怎么生成呢
