### ISSUE TITLE
obj/osg转gltf问题

### ISSUE THREAD

**Issue by dajiang31835008** [fanvanzh/3dtiles#64]
osg/obj模型转换gltf时遇到如下问题：
 1.obj模型（贴图为png格式）转换为gltf时，提示osgdb_png.dll加载失败，看了一下是由于缺少osgdb_png.dll依赖库的问题。我用网上下载的预编译好的vs2015 osg3.4.0(带png插件)替换依赖库，并重新编译3dtile工具。新编译好的工具在调试模式时，在
![image](https://user-images.githubusercontent.com/10216564/51789616-795e2e00-21c5-11e9-8760-fab3111fb562.png)这个位置报如下错误：0x00007FF98FC9A388 处(位于 3dtile.exe 中)引发的异常: Microsoft C++ 异常: std::out_of_range，位于内存位置 0x0000002B70CF6900 处。
0x00007FF98FC9A388 处(位于 3dtile.exe 中)有未经处理的异常: Microsoft C++ 异常: std::out_of_range，位于内存位置 0x0000002B70CF6900 处。
      新编译好的工具在运行模式下，没有报错，也没有生成新的数据。
  2.osg模型转换为gltf时，生成的模型没有贴图，
![image](https://user-images.githubusercontent.com/10216564/51789680-6ef06400-21c6-11e9-9432-04bac4a35964.png)

![image](https://user-images.githubusercontent.com/10216564/51789670-58e2a380-21c6-11e9-9b91-29992aaa8061.png)

**Comment by fanvanzh** [comment]
thank you. 
obj 功能没测试过。

可否发下模型数据，我调试下。

**Comment by dajiang31835008** [comment]
感谢回复！测试数据为同一个模型的两种格式：osg+dds和obj+png
[obj.zip](https://github.com/fanvanzh/3dtiles/files/2803214/obj.zip)

**Comment by fanvanzh** [comment]
现在应该有贴图了
