### ISSUE TITLE
VS2015调试出现问题

### ISSUE THREAD

**Issue by ZoeZhang91** [fanvanzh/3dtiles#66]
调试过程中，TileMaker出现问题：“未能找到类型或命名空间Newtonsoft”等。后重新下载添加新的引用，成功解决；
但是调试vs.sln，无论是WINDOWS还是CONSOLE，均会出现问题：
![image](https://user-images.githubusercontent.com/35569787/53330604-e500fb80-3929-11e9-9552-0b629e61a09f.png)
项目生成失败，
![image](https://user-images.githubusercontent.com/35569787/53330913-a7e93900-392a-11e9-9a84-dbd0f113f6aa.png)

**Comment by fanvanzh** [comment]
这个可能是 debug target 的设置没提交。
你可以自己配置成 （你的目录）\target\debug\3dtile.exe

**Comment by ZoeZhang91** [comment]
谢谢大神，虽然还是LNK2019，但可以调试了。


> 这个可能是 debug target 的设置没提交。
> 你可以自己配置成 （你的目录）\target\debug\3dtile.exe
