### ISSUE TITLE
shape转换后字段属性问题

### ISSUE THREAD

**Issue by junyuz** [fanvanzh/3dtiles#67]
转换后3dtiles中并没有包含属性字段信息，建议把属性信息包含上，更具实用价值

**Comment by fanvanzh** [comment]
谢谢你的建议。

**Comment by suixuejiqiren** [comment]
请问这个问题解决了吗

**Comment by fanvanzh** [comment]
> 请问这个问题解决了吗

抱歉，近期没时间。

**Comment by fanvanzh** [comment]
详见 commit b1e5aa2368e5e96d08e7486699feff70b247a346

**Comment by haolp0511** [comment]
麻烦问下，启动生成tiles 属性字段信息，输入命令是什么，参数是什么？

**Comment by fanvanzh** [comment]
没有参数支持， 你可以参考这个 commit， 自己修改代码实现
