### ISSUE TITLE
prebuild下载之后运行3dtiles.exe执行shape转换程序崩溃

### ISSUE THREAD

**Issue by Immortal-Wang** [fanvanzh/3dtiles#68]
![image](https://user-images.githubusercontent.com/7508940/53618841-10d0f980-3c28-11e9-9784-53b192f35a3e.png)
![image](https://user-images.githubusercontent.com/7508940/53618855-1b8b8e80-3c28-11e9-817e-73ea3f31b018.png)
啥情况？
指令如下：
![image](https://user-images.githubusercontent.com/7508940/53618875-2d6d3180-3c28-11e9-928f-d3d4850d6337.png)

系统环境：WIN10 64位

**Comment by Immortal-Wang** [comment]
系统环境：WIN10 64位

**Comment by fanvanzh** [comment]
--height 后面应该是 表示高度字段的 字段名。

**Comment by Immortal-Wang** [comment]
> --height 后面应该是 表示高度字段的 字段名。

没明白 能给举个例子么？谢谢！

**Comment by fanvanzh** [comment]
3dtile.exe -f shape -i E:\Data\aa.shp -o E:\Data\aa --height height

height 是 shapefile 中的一个字段，表示建筑物的高度。

如果依然崩溃，可上传shapefile，或者加QQ群。

**Comment by Immortal-Wang** [comment]
> 3dtile.exe -f shape -i E:\Data\aa.shp -o E:\Data\aa --height height
> 
> height 是 shapefile 中的一个字段，表示建筑物的高度。
> 
> 如果依然崩溃，可上传shapefile，或者加QQ群。

好的 我上传shape文件用prebuild转换一下试试吧 我这边还是会报错！还有这个height是我的shape文件的自带的字段名么？

**Comment by fanvanzh** [comment]
是的，用你自己shapefile 里的 高度字段 名称。

**Comment by fanvanzh** [comment]
> > 3dtile.exe -f shape -i E:\Data\aa.shp -o E:\Data\aa --height height
> > height 是 shapefile 中的一个字段，表示建筑物的高度。
> > 如果依然崩溃，可上传shapefile，或者加QQ群。
> 
> 好的 我上传shape文件用prebuild转换一下试试吧 我这边还是会报错！还有这个height是我的shape文件的自带的字段名么？

未见上传的 shapefile， 或者加QQ群共享下文件。

**Comment by fanvanzh** [comment]
I think this issue is fixed, please update and try again.
