### ISSUE TITLE
how to update gdal library?

### ISSUE THREAD

**Issue by piaoger** [fanvanzh/3dtiles#69]
我看到gdal库的组织结构好像和网上看到的不一样，是怎么弄的，如果要更新gdal怎么办？

**Comment by fanvanzh** [comment]
替换 gdal 头文件、静态库、动态库 即可。

**Comment by piaoger** [comment]
主要是我看到gdal库有很多文件夹,没有你这个这么干净,比如algo/port/gcore :)
你是把这些头文件手动放一起了吗?


![image](https://user-images.githubusercontent.com/179429/53720981-feabc100-3e9c-11e9-86f1-1c3b3f698054.png)

**Comment by fanvanzh** [comment]
你这是源码。 build 完之后，会有一个 include 目录。

**Comment by piaoger** [comment]
👌
