### ISSUE TITLE
简单的shape通过，复杂的大范围的shape机器像假死

### ISSUE THREAD

**Issue by liyihongcug** [fanvanzh/3dtiles#71]
1台机器直接不能动 
另外1台机器没有死但成了僵死。 但确定这个源文件是能做3dtiles。 数量较大 肯定

**Comment by liyihongcug** [comment]
osgdb 略微复杂的经常有提示某个文件找不到， 健壮性不好

**Comment by fanvanzh** [comment]
> 1台机器直接不能动
> 另外1台机器没有死但成了僵死。 但确定这个源文件是能做3dtiles。 数量较大 肯定

请确认是否是 WGS84 坐标系数据。

**Comment by fanvanzh** [comment]
> osgdb 略微复杂的经常有提示某个文件找不到， 健壮性不好

提示找不到，不影响最终结果。是因为 osgb 有子节点记录，但是文件不存在了。

**Comment by liyihongcug** [comment]
你好。用其他倾斜工具是能转的  不存在找不到的问题。 否则不会提出问题。 我是先验证过本地倾斜数据没有任何问题才说的。 你可以拿数据过去检查额

**Comment by liyihongcug** [comment]
shapefile的 投影
PROJCS["UTM Zone 19, Northern Hemisphere",GEOGCS["Geographic Coordinate System",DATUM["WGS84",SPHEROID["WGS84",6378137,298.257223560493]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-69],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]

**Comment by liyihongcug** [comment]
投影可能我的有问题承认 成功能赚的坐标如下：GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

**Comment by liyihongcug** [comment]
shapefile 分级失败 。LOD这块不行。正常至少能分5级别，当前只有1级 13级测试结果。 
region  BOX 按正常应该也有
