### ISSUE TITLE
shp文件失败

### ISSUE THREAD

**Issue by polluxll** [fanvanzh/3dtiles#72]
数据投影：GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]
数据大小：54M，大量多边形
高程字段：Floor
程序直接停止工作
3dtile.exe -f shape -i D:\Terrain\data\beijing.shp -o D:\Terrain\data\bj --height Floor

**Comment by polluxll** [comment]
从中裁剪了一小块数据，可以正常转化，看来应该是数据量大程序就奔溃了！

**Comment by fanvanzh** [comment]
可以上传 shapefile ，或者 通过 QQ 群分享给我吗？

**Comment by polluxll** [comment]
126363164 QQ群加了一直没有通过
[data.zip](https://github.com/fanvanzh/3dtiles/files/2950450/data.zip)

**Comment by fanvanzh** [comment]
fixed.
