### ISSUE TITLE
b3dm转换第3方来源的b3dm为gltf失败

### ISSUE THREAD

**Issue by liyihongcug** [fanvanzh/3dtiles#73]
3dtile.exe -f b3dm -i E:\Data\aa.b3dm -o E:\Data\aa.glb
如果是3dtile转gltf为 b3dm的 是成功的
但遗憾的 是如果是官方的或者其他平台转换的b3dm。 发现大部分不成功

**Comment by fanvanzh** [comment]
谢谢，没有对接过其他平台转出的 b3dm， 可能某些字节码对不上。
