### ISSUE TITLE
倾斜投影经典的样例数据总是提示找不到某个文件

### ISSUE THREAD

**Issue by liyihongcug** [fanvanzh/3dtiles#74]
3dtile.exe -f osgb -i E:\Data\hgc -o E:\Data\hgc_test
样例数据比较简答是大雁塔倾斜投影数据，有其他工具几个都成功。
另外文件目录超长的时候某明其妙错误， 目录长度似乎有限制

**Comment by fanvanzh** [comment]
谢谢，可否分享下测试数据，和出错目录。
请加QQ群分享下文件。

**Comment by fanvanzh** [comment]
目录中如果包含空格， 请用双引号("")将目录引起来。
大雁塔测试数据，可能L18、L19数据被删了，但是PageLod里有信息，提示找不到不影响最终结果。

如：
3dtile.exe -f osgb -i "E:\backup\我的文档\Tencent Files\FileRecv\大雁塔osgb含测试单体化矢量\osgb" -o C:\Users\Administrator\Desktop\TEST
