### ISSUE TITLE
请问可以用您的代码直接在cesium中读取osgb吗？

### ISSUE THREAD

**Issue by Lizhengest** [fanvanzh/3dtiles#75]
转换过程中直接在cesium读取，请问是可能的吗？虚心请教

**Comment by fanvanzh** [comment]
行不通。Cesium 是 JavaScript的。
你要想在Cesium里直读osgb，方法如下：
1、分析osgb文件格式，找到一手资料。
2、看看有没有js版本的osgb解析库，没有就自己造一个轮子。
3、集成解析osgb的代码，到Cesium中。
