### ISSUE TITLE
osgb转换成glb纹理不显示

### ISSUE THREAD

**Issue by yieryi** [fanvanzh/3dtiles#76]
cesium1.55版本，exe是release1.0版本。测试了两个单个的osgb文件，转换成的glb，使用vscode的glTF Tools插件和windows自带的3d绘图软件验证，均不显示纹理，加载到cesium球上也是无法显示纹理。使用vscode的glTF Tools插件验证glb格式，发现有提示说 "Material does not use texture coordinates sets with indices (0)."。但是转成gltf可以看到有纹理图片

**Comment by fanvanzh** [comment]
thank you。
可否加QQ群，共享下测试文件。

**Comment by yieryi** [comment]
QQ群号多少

**Comment by yieryi** [comment]
共享群进不去呀，付不付费咨询都没反应

**Comment by fanvanzh** [comment]
Thank you for you issue， I will try this issue later.

**Comment by fanvanzh** [comment]
已修复。 # b09fa1f3d249ace3df1504d24596b1af1b32ca54
