### ISSUE TITLE
如何修改源码，解决KHR_technique_webgl  关于版本大于 cesiumlab 1.5的问题

### ISSUE THREAD

**Issue by touwoyimuli** [fanvanzh/3dtiles#77]
请问，想请教一个问题：
问题：
使用.osgb转换.3dtile发布在cesiumlab上面(转换工具https://github.com/fanvanzh/3dtiles)，报错如下RuntimeError: Unsupported glTF Extension: KHR_technique_webgl

网上提供的解决方案，为Cesium.js加载以后，运行以下代码即可正常显示3dtiles数据了。(https://www.jianshu.com/p/e0e0a62c5726?tdsourcetag=s_pctim_aiomsg)（已经验证可行）

提问：但如果我想自己在该github转换工具上面修改源码，使得转换的转换成功之后，在cesiumlab直接发布就可以显示，有可能吗？ 或者有提示方向吗？或者有前辈们已经尝试或实现了这个功能的吗？

备注：版本Cesiumlab(1.5.12, 内置 censium1.55)

**Comment by touwoyimuli** [comment]
或者你有 更新该版本 以支持1.5 版本以上的修复问题  的新版本的想法没有？

**Comment by fanvanzh** [comment]
暂时无考虑。

**Comment by fanvanzh** [comment]
已更新

**Comment by xmuli** [comment]
后面(2019-03)我自己基于二次写了支持了此功能, 但是没有提交 pr, 那会使用 github 不熟练(害)；

现在已经不从事此方向, 不过依旧感谢作者此刻还能回复 issue
