### ISSUE TITLE
osgb to glb - no materials and textures i output file

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [fanvanzh/3dtiles#78]
Hi!

Thanks for making this library. I have tried exporting a osgb file from 3ds max and then converting it to a glb file with the tool. This is how it looks in 3ds max:

![image](https://user-images.githubusercontent.com/10772529/56559771-cf632780-65a2-11e9-99c7-a6ea534ca359.png)

The osgb file is also attached.
[test.zip](https://github.com/fanvanzh/3dtiles/files/3106130/test.zip)

The file is loading in the viewer located here:
https://pissang.github.io/clay-viewer/editor/

But there is no materials or textures displayed.

I also tried the file in these viewers(it does not load and generate an error):
https://sandbox.babylonjs.com/
https://gltf-viewer.donmccurdy.com/

Babylonjs error:
"/meshes/0/primitives/0/material: Failed to find index (10)"

gltf-viewer.donmccurdy error:
"Cannot read property 'extensions' of undefined"
"Validation could not run: TypeError. Cannot read property 'parser' of undefined"

**Comment by fanvanzh** [comment]
Thank you for your report.
I will try your data later.

**Comment by fanvanzh** [comment]
I upload your osgb file to sketchfab.com, some texture image is missing.

I found some bug and have fixed that, now you can try, the result is same as sketchfab.

**Comment by kristiansvenssonwsp** [comment]
Thanks I'll try it out. Is the Windows pre-build version updated?

You probaly need to extract the embedded textures from the osgb. If the textures inside the osgb are compressed this can be done using the command "--compressed -O OutputTextureFiles" in osgconv.exe, something like this:

osgconv --compressed -O OutputTextureFiles test3.osgb dummy.osgt
It will output the compressed dds textures. 

For my exported testfile I choose DXT1 compression:
![image](https://user-images.githubusercontent.com/10772529/56663230-e5a5dc00-66a5-11e9-9322-cb76797e7ecd.png)


I'll also attach another file where the textures are not embedded within the osgb but are exported to an images folder instead.
[test_ext_textures.zip](https://github.com/fanvanzh/3dtiles/files/3112488/test_ext_textures.zip)

**Comment by fanvanzh** [comment]
Yes, Windows pre-build is auto-build by the CI engine after code commit.
DXT1 image is support in this project.

Maybe there are still some bugs when deal with  various of image.

**Comment by kristiansvenssonwsp** [comment]
Great job. Much better now! 

I noticed a few things when doing the first test, here is my summary:

- 2-sided materials don't get converted to 2-sided, they are still single-sided.
- Objects with no materials dont get the color they should have
- Objects that has materials with only a diffuse color (no diffuse map) dont get the color they should have
- Material that have opacity set (for example 50%) don't end up using opacity, they are opaque
- Material that use a png file with alpha channel are rendered without the alpha channel (See the tree and the fence)
- When using DXT1 compressed textures they end up super-pixelated, see this image:

![image](https://user-images.githubusercontent.com/10772529/56743649-43eebf80-6777-11e9-8066-34a697d006bd.png)


For reference I also exported a glb file from 3ds max using the babylon exporter. Here it is:
[test_babylon_gltf_export_nomerge.zip](https://github.com/fanvanzh/3dtiles/files/3117367/test_babylon_gltf_export_nomerge.zip)


It looks quite good in these viewers:
https://sandbox.babylonjs.com/
https://gltf-viewer.donmccurdy.com/

but not very good in:
https://pissang.github.io/clay-viewer/editor/

**Comment by fanvanzh** [comment]
Thank you.

It does take a lot of work to convert obj files into gltf files.
The original purpose of this project is to convert tilt photographic data, which format is more simple.

Make obj file into gltf file, you can search obj2gltf or the same keyword.
I will reference some code to deal with obj file more correctly.

**Comment by fanvanzh** [comment]
Oblique photography is more accuracy.
what I mean is the Smart3D CC product data.

**Comment by rainliang000** [comment]
just now,  i sumit a change to fix dxt1 idx order problem. you can try this.

**Comment by kristiansvenssonwsp** [comment]
Thanks! Dxt1 textures looks nice now
