### ISSUE TITLE
转换出来的数据在cesium1.47上可以加载 在cesium1.53上加载报错

### ISSUE THREAD

**Issue by simonasdmd** [fanvanzh/3dtiles#79]
有几份osgb数据 转换成3dtiles之后 在cesium1.47上可以加载，但是在1.53版本上加载失败，初步怀疑是gltf版本问题，求助下~
ps：咱们这个转换出来的是gltf1.0的吗？
下面是1.53加载的时候的报错
![image](https://user-images.githubusercontent.com/42527845/56707886-4e945f00-674d-11e9-9af4-6829e80a7e48.png)

我百度了下 https://www.jianshu.com/p/e0e0a62c5726 根据这个上面的说明 可以加载。但是数据本身还是1.0的，如果是2.0的应该直接可以加载。

求助大大~~

**Comment by fanzhenhua0401** [comment]
问题解决方案见， #43
