### ISSUE TITLE
转换后的数据问题

### ISSUE THREAD

**Issue by a1144654072** [fanvanzh/3dtiles#8]
![tim 20180327161329](https://user-images.githubusercontent.com/36907597/37958116-338abe76-31e2-11e8-825c-47944a8638bd.png)

为什么会出现数据不在包围盒内的情况？

**Comment by fanvanzh** [comment]
It looks like x or z axis is reverse. I check the code, and soon push a commit, thank you!

**Comment by fanvanzh** [comment]
问题已修复 @a1144654072

**Comment by a1144654072** [comment]
Thank you!

**Comment by a1144654072** [comment]
![tim 20180328153648](https://user-images.githubusercontent.com/36907597/38016070-7dfc70e4-32a0-11e8-940f-a3e7a4491fff.png)
包围盒正确了，但是当我缩放到一定级别的时候，为什么模型会有显示不完整的情况

**Comment by fanvanzh** [comment]
可能是数据的子节点是有osgb文件，但是没有顶点数据。
你是否可以找到消失的瓦片文件，看看原始的 osgb 数据？

**Comment by a1144654072** [comment]
可以把你的QQ发给我吗，我把数据发给你看一下，我这边看是有顶点数据的。

**Comment by fanvanzh** [comment]
你再更新试一下。
