### ISSUE TITLE
转换出来的数据加载层级显示问题

### ISSUE THREAD

**Issue by simonasdmd** [fanvanzh/3dtiles#82]
数据加载的时候，鼠标调整视角，除非拉的特别近，总是有个别块没有和别的块一起同步调整层级。
![image](https://user-images.githubusercontent.com/42527845/57421278-b498e000-723d-11e9-96bd-22da17fc90be.png)

问下这个是osgb的问题还是osgb到3dtiles的转换过程中可以设置的？

**Comment by fanvanzh** [comment]
排除下是不是网络问题，等待一会。

**Comment by simonasdmd** [comment]
不是网络问题，鼠标滚轮再拉近一下视角，就加载出来了， 但是往后面一退，又成这个样子，好几个地方都是这种，周边已经到20级了  然后局部还是停留在十几级

**Comment by simonasdmd** [comment]
@fanvanzh 不是网络问题，鼠标滚轮再拉近一下视角，就加载出来了， 但是往后面一退，又成这个样子，好几个地方都是这种，周边已经到20级了 然后局部还是停留在十几级

**Comment by simonasdmd** [comment]
而且我发下我得osgb数据是有26级的 但是实际转换出来只能显示到24级 我分析是geometricError的原因，因为从24级开始 所有的geometricError都是0了 然后后面的就不加载了

**Comment by fanvanzh** [comment]
0 是最后级别
----- 原始邮件 -----
发件人：simonasdmd <notifications@github.com>
收件人：fanvanzh/3dtiles <3dtiles@noreply.github.com>
抄送人：fanvanzh <fanvanzh@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[fanvanzh/3dtiles]_转换出来的数据加载层级显示问题_(#82)
日期：2019年05月13日 10点10分

而且我发下我得osgb数据是有26级的 但是实际转换出来只能显示到24级 我分析是geometricError的原因，因为从24级开始 所有的geometricError都是0了 然后后面的就不加载了



&mdash;

**Comment by simonasdmd** [comment]
@fanvanzh 0是最后的级别我理解的 就是这个24级对应的0是cesium定的 还是代码里写死的，就是如果有26级的数据应该怎么办？ 能不能劳烦修复下这个问题啊~

**Comment by fanvanzh** [comment]
可能和你的数据情况有关， osgb 文件中 pageload 的最后一层对应 0。
你可以跟踪下代码，看看是否 24 级的 osgb 文件下面没有子节点了。

没有数据，无法为你修复问题。

**Comment by fanvanzh** [comment]
请使用预编译命令行版本。
