### ISSUE TITLE
用vs2017编译报错，请问该如何解决？

### ISSUE THREAD

**Issue by huashaoxu** [fanvanzh/3dtiles#83]
用vs2017编译报错，请问该如何解决，必须要用2015吗？
![image](https://user-images.githubusercontent.com/35364039/57615117-830d7500-75ad-11e9-8981-11f8208f541a.png)

**Comment by fanvanzh** [comment]
是的
----- 原始邮件 -----
发件人：huashaoxu <notifications@github.com>
收件人：fanvanzh/3dtiles <3dtiles@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[fanvanzh/3dtiles]_用vs2017编译报错，请问该如何解决？_(#83)
日期：2019年05月13日 18点33分

用vs2017编译报错，请问该如何解决，必须要用2015吗？






&mdash;
