### ISSUE TITLE
关于3dtileset content uri问题

### ISSUE THREAD

**Issue by huashaoxu** [fanvanzh/3dtiles#84]
3dtileset格式中关于content内的子文件路径，标签名用的是uri，不是url。希望能够修改一下源码，并重新编译下windows预处理。因为在cesium1.48版本以上已经统一支持uri的解析，不再支持url了。

**Comment by fanvanzh** [comment]
是 1.58 版本吧。
1.48 版本我试过，最近半年没有怎么用过了。

**Comment by fanvanzh** [comment]
try again

**Comment by huashaoxu** [comment]
ok
