### ISSUE TITLE
osgb to glb - fail to convert

### ISSUE THREAD

**Issue by kristiansvenssonsweco** [fanvanzh/3dtiles#86]
Hi!
I tried converting the attached osgb to glb but it ends up with the following error:

```
D:\glTF\osgb_3dtiles3>3dtile.exe --format gltf --input vagar2.osgb --output vagar2.glb
InputStream: Failed to read from stream. At osg::Object
ERROR: 2019-05-21 10:47:08 - convert failed
```

Any ideas?
[vagar2.zip](https://github.com/fanvanzh/3dtiles/files/3201593/vagar2.zip)

**Comment by fanvanzh** [comment]
it seems the osgb file can`t be parsed by the drive correctly.

I will try your data later.

**Comment by fanvanzh** [comment]
this osgb file format version is higher than this program used.
you can update the osgb library, and rebuild it.
