### ISSUE TITLE
我有一个osgb的文件夹，他在里面又分成了3个子文件夹。

### ISSUE THREAD

**Issue by gubin15** [fanvanzh/3dtiles#87]
我的倾斜摄影的文件夹里有三个子文件夹分别是Data，Data2，Data3，用您的工具进行转换后只能转换名为Data的文件夹里的文件。其他两个文件夹里的文件都不能转换，我该怎么办？

**Comment by fanvanzh** [comment]
重组成三个目录，然后转成三个 tileset，加载三个。
