### ISSUE TITLE
metaData.xml的格式是啥样的，有个参考案例文件吗？一直提示读取失败

### ISSUE THREAD

**Issue by GitHub-Pen** [fanvanzh/3dtiles#88]

**Comment by fanvanzh** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	
	<SRS>ENU:34.2196,108.9594</SRS>
	
	<SRSOrigin>0,0,0</SRSOrigin>
</ModelMetadata>

**Comment by fanvanzh** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<ModelMetadata version="1">
	<!--Spatial Reference System-->
	<SRS>ENU:34.2196,108.9594</SRS>
	<!--Origin in Spatial Reference System-->
	<SRSOrigin>0,0,0</SRSOrigin>
</ModelMetadata>
```

**Comment by fanvanzh** [comment]
metaData.xml 应该和 Data 目录同级，如果依然错误，排查下文件编码是否为 utf 编码。
谢谢。

**Comment by hellomolike** [comment]
metaData.xml 已经和 Data 目录同级，文件编码也改成 utf-8，还是报`2021-01-04 21:34:04 - D:\Data\Tile_+000_+000\metadata.xml is missing`

**Comment by fanvanzh** [comment]
看上去是文件不存在的意思，确认下有这个文件吗？

**Comment by hellomolike** [comment]
metadata.xml文件存在,内容复制的你给@GitHub-Pen 的回复消息。
<img width="431" alt="1609830536(1)" src="https://user-images.githubusercontent.com/36214418/103618153-68e68e80-4f6a-11eb-8331-d9e7d5175790.png">

**Comment by hellomolike** [comment]
这是我输入的命令行 3dtile.exe -f osgb -i D:\Data\cc\Tile_+000_+000 -o D:\Data\cc\Tile_+000_+000_test，在加一层目录cc后运行这行命令没有报metadata.xml is miss的错误信息。但是仍然出现`ERROR: 2021-01-05 16:38:17 - D:\Data\cc\Tile_+000_+000 does not exists.`说osgb文件找不到了，但是.osgb确实在这个目录之下

**Comment by fanvanzh** [comment]
确认这个目录存在、或者可以被访问吗？
D:\Data\cc\Tile_+000_+000

**Comment by fanvanzh** [comment]
-i 输入数据的目录，osgb数据截止到 "\Data" 目录的上一级

**Comment by xiaoToby** [comment]
@hellomolike  能否提供一下这个数据集？
