### ISSUE TITLE
3dtiles格式问题

### ISSUE THREAD

**Issue by pengbao4386** [fanvanzh/3dtiles#90]
请问转出来的3dtiles文件，在cesium1.50之后就不能用了，是怎么回事啊

**Comment by fanvanzh** [comment]
详见问题 #43 .

周末有时间，我把json格式修改下，不再支持 1.50 之前的版本。

**Comment by rainliang000** [comment]
插件名称修改了, 另外按照gltf2.0的规则json格式也有变化, 可能需要更新下引用的tiny_gltf。

**Comment by fanvanzh** [comment]
already done!
