### ISSUE TITLE
删掉b3dm文件里的着色器代码，就渲染不出来了，是为啥？

### ISSUE THREAD

**Issue by SoulPassenger** [fanvanzh/3dtiles#92]
大神:
       我后续应该如果继续修改文件？

**Comment by fanvanzh** [comment]
生成的 b3dm 不能随意修改，有长度校验等机制的。

通过代码生成 b3dm

**Comment by SoulPassenger** [comment]
我看你源码，好像把着色器添加到了bufferViews里，是不是想办法去掉bufferViews添加的对象，并在头部文件里byteLength去掉着色器长度就好

**Comment by SoulPassenger** [comment]
总结下，需要做3件事：
1.删除着色器代码
2.b3dm头部byteLength去掉着色器占用的长度
3.bufferViews里去掉为着色器添加的对象
