### ISSUE TITLE
转完的b3dm，坐标有偏差

### ISSUE THREAD

**Issue by 346cxh** [fanvanzh/3dtiles#93]

**Comment by 346cxh** [comment]
你好，我的osgb数据里有metadata.xml文件的，用工具转完之后，在cesium可以加载，通过与osgb加载的场景比较，发现同名点坐标存在20米左右的偏差，这个是转换矩阵计算的问题吗

**Comment by fanvanzh** [comment]
有可能，你可以排查下 transform_c 函数。

**Comment by 346cxh** [comment]
楼主，你好，我看了下transform_c，里面调用了transform_xyz来计算转换矩阵，是由于椭球参数不准确造成的位置偏差么，还是什么其他原因呀

**Comment by ThousandsCityFires** [comment]
> 楼主，你好，我看了下transform_c，里面调用了transform_xyz来计算转换矩阵，是由于椭球参数不准确造成的位置偏差么，还是什么其他原因呀

你解决了吗，我这里也是20多米偏差
