### ISSUE TITLE
osgb转换成3dtile后，加载报错

### ISSUE THREAD

**Issue by lijuhong1981** [fanvanzh/3dtiles#94]
![QQ截图20190709175316](https://user-images.githubusercontent.com/3949154/60884825-89079580-a280-11e9-9ecc-844eb6e0aadc.png)
osgb转换成3dtile后，加载时会报这个错
An error occurred while rendering.  Rendering has stopped.
undefined
RuntimeError: Unsupported glTF Extension: KHR_technique_webgl
Error

**Comment by fanvanzh** [comment]
参照 #56
