### ISSUE TITLE
osgb转B3DM的时候，KHR_materials_unlit扩展没有写在extensionsUsed

### ISSUE THREAD

**Issue by wemamawe** [fanvanzh/3dtiles#96]
在GLTF的格式说明里面有下面这句话
> All extensions used in a model are listed as strings in the top-level extensionsUsed array; all required extensions are listed as strings in the top-level extensionsRequired array, e.g.,
![选区_831](https://user-images.githubusercontent.com/29365634/61512234-d677c580-aa2b-11e9-8c81-a7754f85ec81.png)
这个是我转出来之后的文件解析后的，在json.extensionsUsed里没有包含KHR_materials_unlit，反而在json.materials里面有这个扩展

**Comment by fanvanzh** [comment]
没发现 KHR_materials_unlit 这个扩展。

是 gltf 的吗？ 还是 3dtile 的？

**Comment by wemamawe** [comment]
gltf标准里面的

> All extensions used in a model are listed as strings in the top-level extensionsUsed array; all required extensions are listed as strings in the top-level extensionsRequired array, e.g.,

**Comment by wemamawe** [comment]
还有一个问题是，转成b3dm之后，用THREE.GltfLoader进行加载的时候，不加载纹理，我看了一下batchTable的json，是因为Extension写的不正确，另外json.material写的也不正确。

**Comment by fanvanzh** [comment]
这是 cesiumlab 生成的模型， 不是本项目生成的
