### ISSUE TITLE
这个问题是由于OSGB文件3d切片之后缺少高度字段么？

### ISSUE THREAD

**Issue by lihuadong1988** [fanvanzh/3dtiles#97]
![image](https://user-images.githubusercontent.com/18736297/61763210-2200e980-ae07-11e9-8222-8bc0738604ed.png)
![image](https://user-images.githubusercontent.com/18736297/61763226-35ac5000-ae07-11e9-935f-ac2f3410bbb4.png)

**Comment by fanvanzh** [comment]
你这是 3dtile style 吗？
osgb 里没有 height 属性。
shapefile 转 可以指定 height 字段。

**Comment by lihuadong1988** [comment]
嗯，我用shp转成3dtiles可以正常加载，用osgb就不行了。

**Comment by lihuadong1988** [comment]
已经解决了，谢谢。
