### ISSUE TITLE
请问如何在linux下使用

### ISSUE THREAD

**Issue by sazima** [fanvanzh/3dtiles#98]

**Comment by sazima** [comment]
因为是linux, 我跳过了编译指南中的第三步:  `3、下载 rustup-init.exe 自动安装工具并按默认执行， 链接： rustup_init.exe`, 在第五步执行: `cargo build --release`出错

```
➜  3dtiles git:(master) ✗ cargo build --release

warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
    Updating `https://mirrors.ustc.edu.cn/crates.io-index/` index
  Downloaded byteorder v1.3.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded chrono v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded env_logger v0.5.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded clap v2.33.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded libc v0.2.60 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded log v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded rayon v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded serde v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded serde_derive v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded serde_json v1.0.40 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded serde-xml-rs v0.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded num-integer v0.1.41 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded cc v1.0.38 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded time v0.1.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded ansi_term v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded num-traits v0.2.8 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded bitflags v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded atty v0.2.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded strsim v0.8.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded textwrap v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded unicode-width v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded vec_map v0.8.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded humantime v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded termcolor v1.0.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded cfg-if v0.1.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded crossbeam-deque v0.6.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded regex v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded either v1.5.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded rayon-core v1.5.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded autocfg v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded quick-error v1.2.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded log v0.3.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded proc-macro2 v0.4.30 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded quote v0.6.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded xml-rs v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded itoa v0.4.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded ryu v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded aho-corasick v0.7.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded memchr v2.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded syn v0.15.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded thread_local v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded utf8-ranges v1.0.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded regex-syntax v0.6.10 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded crossbeam-epoch v0.7.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded crossbeam-utils v0.6.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded crossbeam-queue v0.1.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded num_cpus v1.10.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded lazy_static v1.3.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded unicode-xid v0.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded ucd-util v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded arrayvec v0.4.11 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded memoffset v0.5.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded scopeguard v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded bitflags v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded nodrop v0.1.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded rustc_version v0.2.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded semver v0.9.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
  Downloaded semver-parser v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling semver-parser v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling arrayvec v0.4.11 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling nodrop v0.1.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling memchr v2.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling cfg-if v0.1.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling libc v0.2.60 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling proc-macro2 v0.4.30 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling autocfg v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling lazy_static v1.3.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling unicode-xid v0.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling scopeguard v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling log v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling ryu v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling serde v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling syn v0.15.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling rayon-core v1.5.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling bitflags v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling ucd-util v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling cc v1.0.38 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling quick-error v1.2.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling unicode-width v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling utf8-ranges v1.0.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling byteorder v1.3.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling bitflags v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling strsim v0.8.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling itoa v0.4.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling ansi_term v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling either v1.5.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling termcolor v1.0.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling vec_map v0.8.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling semver v0.9.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling crossbeam-utils v0.6.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling thread_local v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling num-traits v0.2.8 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling num-integer v0.1.41 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling humantime v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling textwrap v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling regex-syntax v0.6.10 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling xml-rs v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling rustc_version v0.2.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling crossbeam-queue v0.1.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling 3dtile v0.1.0 (/home/wukt/projects/3dtiles)
   Compiling aho-corasick v0.7.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling num_cpus v1.10.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling time v0.1.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling atty v0.2.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling memoffset v0.5.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling log v0.3.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
   Compiling quote v0.6.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)
error: failed to run custom build command for `3dtile v0.1.0 (/home/wukt/projects/3dtiles)`
process didn't exit successfully: `/home/wukt/projects/3dtiles/target/release/build/3dtile-1767a2bf237be427/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/wukt/projects/3dtiles/target/release/build/3dtile-45013d5eb6b0af4b/out/./src/tileset.o" "-c" "./src/tileset.cpp"
cargo:warning=In file included from ./src/gdal/ogr_core.h:34:0,
cargo:warning=                 from ./src/gdal/ogr_srs_api.h:35,
cargo:warning=                 from ./src/gdal/ogr_spatialref.h:35,
cargo:warning=                 from ./src/tileset.cpp:1:
cargo:warning=./src/gdal/cpl_port.h:147:22: fatal error: direct.h: No such file or directory
cargo:warning=compilation terminated.
exit code: 1

--- stderr


error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/wukt/projects/3dtiles/target/release/build/3dtile-45013d5eb6b0af4b/out/./src/tileset.o" "-c" "./src/tileset.cpp" with args "c++" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
error: build failed
➜  3dtiles git:(master) ✗ 

```

**Comment by fanvanzh** [comment]
代码无法在 linux 上编译， 请在 linux 上编译安装 geos、gdal 等 三方库。
----- 原始邮件 -----
发件人：wu kt <notifications@github.com>
收件人：fanvanzh/3dtiles <3dtiles@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[fanvanzh/3dtiles]_请问如何在linux下使用_(#98)
日期：2019年07月25日 10点30分

因为是linux, 我跳过了编译指南中的第三步:  3、下载 rustup-init.exe 自动安装工具并按默认执行， 链接： rustup_init.exe, 在第五步执行: cargo build --release出错

➜  3dtiles git:(master) ✗ cargo build --release



warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future

    Updating `https://mirrors.ustc.edu.cn/crates.io-index/` index

  Downloaded byteorder v1.3.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded chrono v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded env_logger v0.5.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded clap v2.33.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded libc v0.2.60 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded log v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded rayon v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded serde v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded serde_derive v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded serde_json v1.0.40 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded serde-xml-rs v0.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded num-integer v0.1.41 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded cc v1.0.38 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded time v0.1.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded ansi_term v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded num-traits v0.2.8 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded bitflags v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded atty v0.2.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded strsim v0.8.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded textwrap v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded unicode-width v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded vec_map v0.8.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded humantime v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded termcolor v1.0.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded cfg-if v0.1.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded crossbeam-deque v0.6.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded regex v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded either v1.5.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded rayon-core v1.5.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded autocfg v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded quick-error v1.2.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded log v0.3.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded proc-macro2 v0.4.30 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded quote v0.6.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded xml-rs v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded itoa v0.4.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded ryu v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded aho-corasick v0.7.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded memchr v2.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded syn v0.15.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded thread_local v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded utf8-ranges v1.0.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded regex-syntax v0.6.10 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded crossbeam-epoch v0.7.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded crossbeam-utils v0.6.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded crossbeam-queue v0.1.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded num_cpus v1.10.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded lazy_static v1.3.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded unicode-xid v0.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded ucd-util v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded arrayvec v0.4.11 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded memoffset v0.5.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded scopeguard v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded bitflags v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded nodrop v0.1.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded rustc_version v0.2.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded semver v0.9.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

  Downloaded semver-parser v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling semver-parser v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling arrayvec v0.4.11 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling nodrop v0.1.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling memchr v2.2.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling cfg-if v0.1.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling libc v0.2.60 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling proc-macro2 v0.4.30 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling autocfg v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling lazy_static v1.3.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling unicode-xid v0.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling scopeguard v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling log v0.4.7 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling ryu v1.0.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling serde v1.0.97 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling syn v0.15.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling rayon-core v1.5.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling bitflags v1.1.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling ucd-util v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling cc v1.0.38 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling quick-error v1.2.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling unicode-width v0.1.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling utf8-ranges v1.0.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling byteorder v1.3.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling bitflags v0.7.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling strsim v0.8.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling itoa v0.4.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling ansi_term v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling either v1.5.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling termcolor v1.0.5 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling vec_map v0.8.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling semver v0.9.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling crossbeam-utils v0.6.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling thread_local v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling num-traits v0.2.8 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling num-integer v0.1.41 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling humantime v1.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling textwrap v0.11.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling regex-syntax v0.6.10 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling xml-rs v0.3.6 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling rustc_version v0.2.3 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling crossbeam-queue v0.1.2 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling 3dtile v0.1.0 (/home/wukt/projects/3dtiles)

   Compiling aho-corasick v0.7.4 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling num_cpus v1.10.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling time v0.1.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling atty v0.2.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling memoffset v0.5.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling log v0.3.9 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

   Compiling quote v0.6.13 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)

error: failed to run custom build command for `3dtile v0.1.0 (/home/wukt/projects/3dtiles)`

process didn't exit successfully: `/home/wukt/projects/3dtiles/target/release/build/3dtile-1767a2bf237be427/build-script-build` (exit code: 1)

--- stdout

TARGET = Some("x86_64-unknown-linux-gnu")

OPT_LEVEL = Some("3")

HOST = Some("x86_64-unknown-linux-gnu")

CXX_x86_64-unknown-linux-gnu = None

CXX_x86_64_unknown_linux_gnu = None

HOST_CXX = None

CXX = None

CXXFLAGS_x86_64-unknown-linux-gnu = None

CXXFLAGS_x86_64_unknown_linux_gnu = None

HOST_CXXFLAGS = None

CXXFLAGS = None

CRATE_CC_NO_DEFAULTS = None

DEBUG = Some("false")

CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/wukt/projects/3dtiles/target/release/build/3dtile-45013d5eb6b0af4b/out/./src/tileset.o" "-c" "./src/tileset.cpp"

cargo:warning=In file included from ./src/gdal/ogr_core.h:34:0,

cargo:warning=                 from ./src/gdal/ogr_srs_api.h:35,

cargo:warning=                 from ./src/gdal/ogr_spatialref.h:35,

cargo:warning=                 from ./src/tileset.cpp:1:

cargo:warning=./src/gdal/cpl_port.h:147:22: fatal error: direct.h: No such file or directory

cargo:warning=compilation terminated.

exit code: 1



--- stderr





error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "./src" "-I" "./src/osg" "-std=c++11" "-o" "/home/wukt/projects/3dtiles/target/release/build/3dtile-45013d5eb6b0af4b/out/./src/tileset.o" "-c" "./src/tileset.cpp" with args "c++" did not execute successfully (status code exit code: 1).







warning: build failed, waiting for other jobs to finish...

error: build failed

➜  3dtiles git:(master) ✗ 







&mdash;

**Comment by sazima** [comment]
感谢回答. 可惜不熟悉rust, 最后是在win下转换的

**Comment by sazima** [comment]
期待有个linux版文档, 或者linux用户提pr

**Comment by sazima** [comment]
```
cargo:warning=./src/gdal/cpl_port.h:147:22: fatal error: direct.h: No such file or directory
```

我找到了一些回答: 
`Commonly, is a C/C++ header file provided by Microsoft Windows, so it cannot works in linux.`

https://stackoverflow.com/questions/6193607/cannot-find-direct-h

http://angband.oook.cz/forum/showthread.php?t=6446

**Comment by fanvanzh** [comment]
支持了，阉割了 shpfile 和 gdal 库。

https://github.com/fanvanzh/3dtiles/wiki/How-to-build#linux-%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E
